<?xml version="1.0"?>
<!DOCTYPE XML[
<!ELEMENT XML (X0*,T*)>
<!ELEMENT X0 (X1*,T*)>
<!ELEMENT X1 (X2*,T*)>
<!ELEMENT X2 (X3*,T*)>
<!ELEMENT X3 (X4*,T*)>
<!ELEMENT X4 (X5*,T*)>
<!ELEMENT X5 (X6*,T*)>
<!ELEMENT X6 (X7*,T*)>
<!ELEMENT X7 (X8*,T*)>
<!ELEMENT X8 (X9*,T*)>
<!ELEMENT X9 (EMPTY)>
<!ELEMENT T (#PCDATA)>
<!ATTLIST X0 A0 CDATA #IMPLIED>
<!ATTLIST X0 A1 CDATA #IMPLIED>
<!ATTLIST X0 A2 CDATA #IMPLIED>
<!ATTLIST X0 A3 CDATA #IMPLIED>
<!ATTLIST X0 A4 CDATA #IMPLIED>
<!ATTLIST X0 A5 CDATA #IMPLIED>
<!ATTLIST X0 A6 CDATA #IMPLIED>
<!ATTLIST X0 A7 CDATA #IMPLIED>
<!ATTLIST X0 A8 CDATA #IMPLIED>
<!ATTLIST X0 A9 CDATA #IMPLIED>
<!ATTLIST X1 A0 CDATA #IMPLIED>
<!ATTLIST X1 A1 CDATA #IMPLIED>
<!ATTLIST X1 A2 CDATA #IMPLIED>
<!ATTLIST X1 A3 CDATA #IMPLIED>
<!ATTLIST X1 A4 CDATA #IMPLIED>
<!ATTLIST X1 A5 CDATA #IMPLIED>
<!ATTLIST X1 A6 CDATA #IMPLIED>
<!ATTLIST X1 A7 CDATA #IMPLIED>
<!ATTLIST X1 A8 CDATA #IMPLIED>
<!ATTLIST X1 A9 CDATA #IMPLIED>
<!ATTLIST X2 A0 CDATA #IMPLIED>
<!ATTLIST X2 A1 CDATA #IMPLIED>
<!ATTLIST X2 A2 CDATA #IMPLIED>
<!ATTLIST X2 A3 CDATA #IMPLIED>
<!ATTLIST X2 A4 CDATA #IMPLIED>
<!ATTLIST X2 A5 CDATA #IMPLIED>
<!ATTLIST X2 A6 CDATA #IMPLIED>
<!ATTLIST X2 A7 CDATA #IMPLIED>
<!ATTLIST X2 A8 CDATA #IMPLIED>
<!ATTLIST X2 A9 CDATA #IMPLIED>
<!ATTLIST X3 A0 CDATA #IMPLIED>
<!ATTLIST X3 A1 CDATA #IMPLIED>
<!ATTLIST X3 A2 CDATA #IMPLIED>
<!ATTLIST X3 A3 CDATA #IMPLIED>
<!ATTLIST X3 A4 CDATA #IMPLIED>
<!ATTLIST X3 A5 CDATA #IMPLIED>
<!ATTLIST X3 A6 CDATA #IMPLIED>
<!ATTLIST X3 A7 CDATA #IMPLIED>
<!ATTLIST X3 A8 CDATA #IMPLIED>
<!ATTLIST X3 A9 CDATA #IMPLIED>
<!ATTLIST X4 A0 CDATA #IMPLIED>
<!ATTLIST X4 A1 CDATA #IMPLIED>
<!ATTLIST X4 A2 CDATA #IMPLIED>
<!ATTLIST X4 A3 CDATA #IMPLIED>
<!ATTLIST X4 A4 CDATA #IMPLIED>
<!ATTLIST X4 A5 CDATA #IMPLIED>
<!ATTLIST X4 A6 CDATA #IMPLIED>
<!ATTLIST X4 A7 CDATA #IMPLIED>
<!ATTLIST X4 A8 CDATA #IMPLIED>
<!ATTLIST X4 A9 CDATA #IMPLIED>
<!ATTLIST X5 A0 CDATA #IMPLIED>
<!ATTLIST X5 A1 CDATA #IMPLIED>
<!ATTLIST X5 A2 CDATA #IMPLIED>
<!ATTLIST X5 A3 CDATA #IMPLIED>
<!ATTLIST X5 A4 CDATA #IMPLIED>
<!ATTLIST X5 A5 CDATA #IMPLIED>
<!ATTLIST X5 A6 CDATA #IMPLIED>
<!ATTLIST X5 A7 CDATA #IMPLIED>
<!ATTLIST X5 A8 CDATA #IMPLIED>
<!ATTLIST X5 A9 CDATA #IMPLIED>
<!ATTLIST X6 A0 CDATA #IMPLIED>
<!ATTLIST X6 A1 CDATA #IMPLIED>
<!ATTLIST X6 A2 CDATA #IMPLIED>
<!ATTLIST X6 A3 CDATA #IMPLIED>
<!ATTLIST X6 A4 CDATA #IMPLIED>
<!ATTLIST X6 A5 CDATA #IMPLIED>
<!ATTLIST X6 A6 CDATA #IMPLIED>
<!ATTLIST X6 A7 CDATA #IMPLIED>
<!ATTLIST X6 A8 CDATA #IMPLIED>
<!ATTLIST X6 A9 CDATA #IMPLIED>
<!ATTLIST X7 A0 CDATA #IMPLIED>
<!ATTLIST X7 A1 CDATA #IMPLIED>
<!ATTLIST X7 A2 CDATA #IMPLIED>
<!ATTLIST X7 A3 CDATA #IMPLIED>
<!ATTLIST X7 A4 CDATA #IMPLIED>
<!ATTLIST X7 A5 CDATA #IMPLIED>
<!ATTLIST X7 A6 CDATA #IMPLIED>
<!ATTLIST X7 A7 CDATA #IMPLIED>
<!ATTLIST X7 A8 CDATA #IMPLIED>
<!ATTLIST X7 A9 CDATA #IMPLIED>
<!ATTLIST X8 A0 CDATA #IMPLIED>
<!ATTLIST X8 A1 CDATA #IMPLIED>
<!ATTLIST X8 A2 CDATA #IMPLIED>
<!ATTLIST X8 A3 CDATA #IMPLIED>
<!ATTLIST X8 A4 CDATA #IMPLIED>
<!ATTLIST X8 A5 CDATA #IMPLIED>
<!ATTLIST X8 A6 CDATA #IMPLIED>
<!ATTLIST X8 A7 CDATA #IMPLIED>
<!ATTLIST X8 A8 CDATA #IMPLIED>
<!ATTLIST X8 A9 CDATA #IMPLIED>
<!ATTLIST X9 A0 CDATA #IMPLIED>
<!ATTLIST X9 A1 CDATA #IMPLIED>
<!ATTLIST X9 A2 CDATA #IMPLIED>
<!ATTLIST X9 A3 CDATA #IMPLIED>
<!ATTLIST X9 A4 CDATA #IMPLIED>
<!ATTLIST X9 A5 CDATA #IMPLIED>
<!ATTLIST X9 A6 CDATA #IMPLIED>
<!ATTLIST X9 A7 CDATA #IMPLIED>
<!ATTLIST X9 A8 CDATA #IMPLIED>
<!ATTLIST X9 A9 CDATA #IMPLIED>
]>
<XML>
  <X0 A0="COMMENT">
    <T>P=PARAMETER;PS=PARAMETERS;T=TRIAL;TS=TRIALS;TPS=TRIALPARAMTERS;
	DP=DATAPOINT;DPS=DATAPOINTS;DPPS=DATAPOINTSPARAMETERS
	PARAMETER:
	N=NAME;P=protection code : U=USER;E=EXPERIMENT
	T=TYPE
	D = extra tag data dictionary</T>
  </X0>
  <X0 A0="PS">
    <X1 A0="P" A1="UPDCREATED" A2="UPD040907" A3="E" />
    <X1 A0="P" A1="IMPORTFILEDATA" A2="14/06/2018 15:56:18" A3="S" />
    <X1 A0="P" A1="FILENAME" A2="14/06/2018 15:56:18" A3="S" />
    <X1 A0="P" A1="EXP:DATATYPE" A2="LEUVEN2007:data" A3="E" />
    <X1 A0="P" A1="VOLFLOW" A2="T" A3="E" />
    <X1 A0="P" A1="FROMAFFECT" A2="T" A3="E" />
    <X1 A0="P" A1="PNEUMOSCRIPT" A2="" A3="E" />
    <X1 A0="P" A1="CH7:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="CH8:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="MAXSAMPLES" A2="154497" A3="E" />
    <X1 A0="P" A1="PROFILE" A2="LEUVEN2007" A3="E" />
    <X1 A0="P" A1="PHUID" A2="4905" A3="U" />
    <X1 A0="P" A1="CH2DISPLAY" A2="DisplayON=T;MyName=CH8;DType=12;Upper=51810000;Lower=50000;Persistent=T;;DType=12;MyName=W1;Upper=22996410;Persistent=T;Lower=-1276691.5;;MyName=W2;DType=12;Upper=0;Persistent=T;Lower=0;;DType=12;MyName=W3;Upper=51810000;Persistent=T;Lower=50000;;DType=12;MyName=CH7;Upper=5181;Lower=5;Persistent=T;;DType=1;MyName=X;Upper=1001;Lower=0;Persistent=T" A3="U" />
    <X1 A0="P" A1="SHOWSTRIPEMODE" A2="ALL" A3="U" />
    <X1 A0="P" A1="CURRENTCH" A2="CH8" A3="U" />
    <X1 A0="P" A1="DATEMARKER" A2="1806180845" A3="U" />
    <X1 A0="P" A1="HIDEMARKERS" A2="" A3="U" />
    <X1 A0="P" A1="OUT_CH8BIS" A2="OUTPUTEXT=&quot;.EMGBIS.CSV&quot;;DISPLAYWITH=&quot;CH7&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_MEAN=&quot;MEAN&quot;;EMG_MAXGENT=&quot;MAXGENT&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_AMPL=&quot;AMPLITUDO&quot;;EMG_LMAX=&quot;LATENCYMAX&quot;;EMG_L3XLR=&quot;LATNCY3XLR&quot;;EMG_L3XRL=&quot;LATNCY3XRL&quot;;EMG_L3XDIF=&quot;LATNCY3XDIF&quot;;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SPECIALGROUP" A2="" A3="U" />
    <X1 A0="P" A1="EMG:SENS100" A2="100" A3="U" />
    <X1 A0="P" A1="EMG:SENS1000" A2="1000" A3="U" />
    <X1 A0="P" A1="EMG:SENS5000" A2="5000" A3="U" />
    <X1 A0="P" A1="EMG:SENS10000" A2="10000" A3="U" />
    <X1 A0="P" A1="EMG:SENS50000" A2="50000" A3="U" />
    <X1 A0="P" A1="OUT_CH8" A2="OUTPUTEXT=&quot;.EMG.CSV&quot;;DISPLAYWITH=&quot;CH8&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_BL=&quot;BASELINE&quot;;EMG_MAXLEUVEN=&quot;MAXLEUVEN&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_REJECT=&quot;REJECT&quot;;EMG_NON_RESPONS=&quot;NON_RESPPONS&quot;;CH8:PAS:Stimulus#G=Stimulus;CH8:PAS:Total_Trial_Nr#G=Total_Trial_Nr;CH8:PAS:practice#G=practice;CH8:PAS:acq#G=acq;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SRCFILEINFO" A2="" A3="U" />
  </X0>
  <X0 A0="iLOG" />
  <X0 A0="TS">
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="1" A3="S" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="1" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
        <X3 A0="P" A1="CH7REPOTR" A2="" A3="U" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'14/06/2018 15:56:18'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;538095,238&quot;;EMG_MAXLEUVEN=&quot;0701,000&quot;;EMG_MAXV=&quot;1200000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0000,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0001,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806180845,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="538095.238095238" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="48994.7919554355" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="701" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 1141742" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="535924.794642857" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'14/06/2018 15:56:18'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;535924,795&quot;;EMG_MAXGENT=&quot;0705,000&quot;;EMG_MAXV=&quot;1141742,000&quot;;EMG_AMPL=&quot;605817,205&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;9999,000&quot;;EMG_L3XRL=&quot;9999,000&quot;;EMG_L3XDIF=&quot;9999,000&quot;;DATEMARKER#G=&quot;1806180845,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="705" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="1607774.38392857" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="605817.205357143" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=48994.7919554355" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=535924.794642857" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1071" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=42" A2="S=OK;V=500;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1070;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;86;83;80;75;72;74;73;72;72;72;70;69;76;76;75;78;79;76;76;76;</T>
            <T>;79;82;81;80;82;84;82;80;79;77;76;74;73;74;72;70;68;66;63;61;</T>
            <T>;63;69;76;82;79;77;76;77;80;86;93;95;94;91;88;87;83;80;78;75;</T>
            <T>;72;70;74;77;74;73;73;72;69;69;70;70;73;73;71;70;71;72;73;76;</T>
            <T>;78;80;80;80;83;84;82;80;79;75;74;76;75;73;74;72;70;70;75;75;</T>
            <T>;75;74;72;70;71;75;75;73;72;71;70;70;69;67;65;62;61;60;58;56;</T>
            <T>;57;57;54;55;55;54;56;59;58;56;55;54;59;57;56;59;60;59;58;58;</T>
            <T>;59;56;54;53;54;52;52;55;60;61;60;59;63;65;64;63;62;63;61;65;</T>
            <T>;68;68;71;74;71;69;66;65;64;65;63;63;70;68;68;76;83;81;80;79;</T>
            <T>;76;73;68;69;71;70;70;69;70;68;70;68;68;67;65;63;62;60;62;65;</T>
            <T>;65;64;61;63;64;63;66;69;69;66;63;62;62;61;59;57;56;57;56;56;</T>
            <T>;57;58;58;57;60;59;59;59;62;63;59;57;58;57;57;56;56;59;58;57;</T>
            <T>;55;56;53;53;54;56;57;58;61;59;59;60;63;64;65;63;62;65;65;66;</T>
            <T>;66;66;64;61;60;58;56;56;55;58;67;70;70;67;65;64;62;62;67;69;</T>
            <T>;70;68;65;66;67;65;64;62;60;60;59;61;63;64;64;63;61;61;67;68;</T>
            <T>;67;67;62;61;60;61;59;57;56;55;54;56;60;64;64;63;61;60;59;63;</T>
            <T>;65;63;58;58;56;56;56;55;56;55;53;54;56;56;55;52;51;51;48;50;</T>
            <T>;54;58;59;58;56;55;54;51;52;49;47;46;46;45;44;47;47;45;43;45;</T>
            <T>;48;47;48;47;48;45;44;44;45;46;46;49;54;53;53;54;55;59;58;61;</T>
            <T>;61;61;59;59;63;62;60;58;56;56;54;57;60;62;62;60;61;63;62;62;</T>
            <T>;63;66;67;66;65;64;66;72;75;73;70;69;71;71;67;66;63;61;61;63;</T>
            <T>;66;63;59;60;63;69;69;72;71;68;68;68;70;70;73;70;68;65;64;62;</T>
            <T>;60;62;61;60;58;57;57;58;58;58;59;59;61;65;67;66;66;64;65;65;</T>
            <T>;64;62;61;60;58;62;64;64;62;61;60;59;59;57;56;55;55;60;62;62;</T>
            <T>;66;71;75;80;78;75;73;72;72;72;68;68;69;66;65;62;60;58;57;60;</T>
            <T>;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;</T>
            <T>;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;58;</T>
            <T>;58;58;58;56;53;53;52;51;52;51;52;49;47;45;46;49;49;48;50;53;</T>
            <T>;55;60;61;60;59;57;57;60;58;57;58;56;54;53;56;58;58;59;57;56;</T>
            <T>;54;53;53;53;51;50;49;52;53;52;52;50;49;48;49;49;48;47;49;53;</T>
            <T>;52;52;51;51;48;47;48;47;47;46;46;43;41;42;43;44;45;46;47;50;</T>
            <T>;50;49;48;50;46;46;45;48;49;49;47;44;43;44;45;46;44;44;46;53;</T>
            <T>;60;63;62;67;73;83;90;93;93;91;91;87;83;81;80;77;77;74;74;71;</T>
            <T>;68;68;68;73;75;73;71;69;68;67;66;69;66;64;65;65;63;62;68;70;</T>
            <T>;77;84;88;94;97;94;92;88;91;95;93;89;87;87;92;91;102;111;111;111;</T>
            <T>;113;120;117;118;116;113;109;109;109;109;109;107;103;100;100;97;95;92;88;85;</T>
            <T>;84;83;82;79;75;75;74;73;71;70;74;74;74;73;74;73;70;68;66;63;</T>
            <T>;61;61;61;62;59;57;55;53;52;52;55;56;54;53;53;53;52;52;52;50;</T>
            <T>;48;48;51;55;56;53;53;53;51;50;53;54;56;56;54;54;55;55;55;55;</T>
            <T>;56;56;53;52;51;51;50;46;46;45;51;51;51;52;51;48;46;46;47;47;</T>
            <T>;47;47;46;48;52;51;52;55;55;53;53;50;50;50;50;49;48;46;44;42;</T>
            <T>;43;43;43;43;43;42;43;43;44;45;45;44;44;42;46;55;63;63;61;59;</T>
            <T>;59;60;64;64;62;62;61;59;57;55;54;53;54;59;59;62;63;61;59;56;</T>
            <T>;55;53;56;56;56;56;56;58;59;57;58;57;56;56;55;53;53;54;55;53;</T>
            <T>;53;53;52;49;52;52;56;56;56;54;52;52;58;59;57;55;55;55;55;58;</T>
            <T>;57;55;55;53;50;48;46;46;50;50;49;47;46;46;45;45;49;48;48;47;</T>
            <T>;47;53;60;62;61;59;58;59;61;60;59;59;60;61;60;57;56;55;54;57;</T>
            <T>;61;59;59;58;58;57;58;57;57;61;61;59;61;61;63;70;75;73;74;79;</T>
            <T>;82;86;86;82;82;83;82;78;77;75;72;70;68;67;68;68;65;63;62;64;</T>
            <T>;62;59;59;59;63;64;64;67;67;67;66;67;66;62;61;63;64;64;63;61;</T>
            <T>;60;61;61;60;58;57;55;52;52;52;52;54;53;54;54;52;51;50;50;50;</T>
            <T>;50;49;47;45;44;43;47;54;53;51;51;50;50;51;50;49;48;46;44;44;</T>
            <T>;48;48;48;49;50;48;47;46;46;45;47;45;45;47;48;48;47;45;46;46;</T>
            <T>;48;47;49;49;48;47;47;47;50;49;47;</T>
          </X4>
        </X3>
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH8" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1071" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="#OK" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=42" A2="S=OK;V=500;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="MAX" A2="A=602621.25;S=OK;V=569;C=16711935;PHUID=PH1099;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=505625.28;S=OK;V=585;C=8421376;PHUID=PH1104;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=521238;S=OK;V=593;C=16711935;PHUID=PH1100;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=448582.62;S=OK;V=608;C=8421376;PHUID=PH1105;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=483539.84;S=OK;V=619;C=16711935;PHUID=PH1101;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=432689.06;S=OK;V=630;C=8421376;PHUID=PH1106;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=867571.5;S=OK;V=651;C=16711935;PHUID=PH1102;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=633957.62;S=OK;V=668;C=8421376;PHUID=PH1107;E=0" A3="U" />
            <X5 A0="M" A1="MAXLEUVEN" A2="TCOLOR=65280;A=0;S=OK;V=701;C=65280;PHUID=PH1109;E=0" A3="U" />
            <X5 A0="M" A1="MAXGENT" A2="TCOLOR=16711935;A=0;S=OK;V=705;C=16711935;PHUID=PH1108;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="C=16711935;E=0;SHM=ON;V=705;PHUID=PH1103;S=HIDE;A=1141742.12" A3="U" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1070;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;860000;830000;800000;750000;720000;740000;730000;720000;720000;720000;700000;690000;760000;760000;750000;780000;790000;760000;760000;760000;</T>
            <T>;790000;820000;810000;800000;820000;840000;820000;800000;790000;770000;760000;740000;730000;740000;720000;700000;680000;660000;630000;610000;</T>
            <T>;630000;690000;760000;820000;790000;770000;760000;770000;800000;860000;930000;950000;940000;910000;880000;870000;830000;800000;780000;750000;</T>
            <T>;720000;700000;740000;770000;740000;730000;730000;720000;690000;690000;700000;700000;730000;730000;710000;700000;710000;720000;730000;760000;</T>
            <T>;780000;800000;800000;800000;830000;840000;820000;800000;790000;750000;740000;760000;750000;730000;740000;720000;700000;700000;750000;750000;</T>
            <T>;750000;740000;720000;700000;710000;750000;750000;730000;720000;710000;700000;700000;690000;670000;650000;620000;610000;600000;580000;560000;</T>
            <T>;570000;570000;540000;550000;550000;540000;560000;590000;580000;560000;550000;540000;590000;570000;560000;590000;600000;590000;580000;580000;</T>
            <T>;590000;560000;540000;530000;540000;520000;520000;550000;600000;610000;600000;590000;630000;650000;640000;630000;620000;630000;610000;650000;</T>
            <T>;680000;680000;710000;740000;710000;690000;660000;650000;640000;650000;630000;630000;700000;680000;680000;760000;830000;810000;800000;790000;</T>
            <T>;760000;730000;680000;690000;710000;700000;700000;690000;700000;680000;700000;680000;680000;670000;650000;630000;620000;600000;620000;650000;</T>
            <T>;650000;640000;610000;630000;640000;630000;660000;690000;690000;660000;630000;620000;620000;610000;590000;570000;560000;570000;560000;560000;</T>
            <T>;570000;580000;580000;570000;600000;590000;590000;590000;620000;630000;590000;570000;580000;570000;570000;560000;560000;590000;580000;570000;</T>
            <T>;550000;560000;530000;530000;540000;560000;570000;580000;610000;590000;590000;600000;630000;640000;650000;630000;620000;650000;650000;660000;</T>
            <T>;660000;660000;640000;610000;600000;580000;560000;560000;550000;580000;670000;700000;700000;670000;650000;640000;620000;620000;670000;690000;</T>
            <T>;700000;680000;650000;660000;670000;650000;640000;620000;600000;600000;590000;610000;630000;640000;640000;630000;610000;610000;670000;680000;</T>
            <T>;670000;670000;620000;610000;600000;610000;590000;570000;560000;550000;540000;560000;600000;640000;640000;630000;610000;600000;590000;630000;</T>
            <T>;650000;630000;580000;580000;560000;560000;560000;550000;560000;550000;530000;540000;560000;560000;550000;520000;510000;510000;480000;500000;</T>
            <T>;540000;580000;590000;580000;560000;550000;540000;510000;520000;490000;470000;460000;460000;450000;440000;470000;470000;450000;430000;450000;</T>
            <T>;480000;470000;480000;470000;480000;450000;440000;440000;450000;460000;460000;490000;540000;530000;530000;540000;550000;590000;580000;610000;</T>
            <T>;610000;610000;590000;590000;630000;620000;600000;580000;560000;560000;540000;570000;600000;620000;620000;600000;610000;630000;620000;620000;</T>
            <T>;630000;660000;670000;660000;650000;640000;660000;720000;750000;730000;700000;690000;710000;710000;670000;660000;630000;610000;610000;630000;</T>
            <T>;660000;630000;590000;600000;630000;690000;690000;720000;710000;680000;680000;680000;700000;700000;730000;700000;680000;650000;640000;620000;</T>
            <T>;600000;620000;610000;600000;580000;570000;570000;580000;580000;580000;590000;590000;610000;650000;670000;660000;660000;640000;650000;650000;</T>
            <T>;640000;620000;610000;600000;580000;620000;640000;640000;620000;610000;600000;590000;590000;570000;560000;550000;550000;600000;620000;620000;</T>
            <T>;660000;710000;750000;800000;780000;750000;730000;720000;720000;720000;680000;680000;690000;660000;650000;620000;600000;580000;570000;600000;</T>
            <T>;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;</T>
            <T>;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;580000;</T>
            <T>;580000;580000;580000;560000;530000;530000;520000;510000;520000;510000;520000;490000;470000;450000;460000;490000;490000;480000;500000;530000;</T>
            <T>;550000;600000;610000;600000;590000;570000;570000;600000;580000;570000;580000;560000;540000;530000;560000;580000;580000;590000;570000;560000;</T>
            <T>;540000;530000;530000;530000;510000;500000;490000;520000;530000;520000;520000;500000;490000;480000;490000;490000;480000;470000;490000;530000;</T>
            <T>;520000;520000;510000;510000;480000;470000;480000;470000;470000;460000;460000;430000;410000;420000;430000;440000;450000;460000;470000;500000;</T>
            <T>;500000;490000;480000;500000;460000;460000;450000;480000;490000;490000;470000;440000;430000;440000;450000;460000;440000;440000;460000;530000;</T>
            <T>;600000;630000;620000;670000;730000;830000;900000;930000;930000;910000;910000;870000;830000;810000;800000;770000;770000;740000;740000;710000;</T>
            <T>;680000;680000;680000;730000;750000;730000;710000;690000;680000;670000;660000;690000;660000;640000;650000;650000;630000;620000;680000;700000;</T>
            <T>;770000;840000;880000;940000;970000;940000;920000;880000;910000;950000;930000;890000;870000;870000;920000;910000;1020000;1110000;1110000;1110000;</T>
            <T>;1130000;1200000;1170000;1180000;1160000;1130000;1090000;1090000;1090000;1090000;1090000;1070000;1030000;1000000;1000000;970000;950000;920000;880000;850000;</T>
            <T>;840000;830000;820000;790000;750000;750000;740000;730000;710000;700000;740000;740000;740000;730000;740000;730000;700000;680000;660000;630000;</T>
            <T>;610000;610000;610000;620000;590000;570000;550000;530000;520000;520000;550000;560000;540000;530000;530000;530000;520000;520000;520000;500000;</T>
            <T>;480000;480000;510000;550000;560000;530000;530000;530000;510000;500000;530000;540000;560000;560000;540000;540000;550000;550000;550000;550000;</T>
            <T>;560000;560000;530000;520000;510000;510000;500000;460000;460000;450000;510000;510000;510000;520000;510000;480000;460000;460000;470000;470000;</T>
            <T>;470000;470000;460000;480000;520000;510000;520000;550000;550000;530000;530000;500000;500000;500000;500000;490000;480000;460000;440000;420000;</T>
            <T>;430000;430000;430000;430000;430000;420000;430000;430000;440000;450000;450000;440000;440000;420000;460000;550000;630000;630000;610000;590000;</T>
            <T>;590000;600000;640000;640000;620000;620000;610000;590000;570000;550000;540000;530000;540000;590000;590000;620000;630000;610000;590000;560000;</T>
            <T>;550000;530000;560000;560000;560000;560000;560000;580000;590000;570000;580000;570000;560000;560000;550000;530000;530000;540000;550000;530000;</T>
            <T>;530000;530000;520000;490000;520000;520000;560000;560000;560000;540000;520000;520000;580000;590000;570000;550000;550000;550000;550000;580000;</T>
            <T>;570000;550000;550000;530000;500000;480000;460000;460000;500000;500000;490000;470000;460000;460000;450000;450000;490000;480000;480000;470000;</T>
            <T>;470000;530000;600000;620000;610000;590000;580000;590000;610000;600000;590000;590000;600000;610000;600000;570000;560000;550000;540000;570000;</T>
            <T>;610000;590000;590000;580000;580000;570000;580000;570000;570000;610000;610000;590000;610000;610000;630000;700000;750000;730000;740000;790000;</T>
            <T>;820000;860000;860000;820000;820000;830000;820000;780000;770000;750000;720000;700000;680000;670000;680000;680000;650000;630000;620000;640000;</T>
            <T>;620000;590000;590000;590000;630000;640000;640000;670000;670000;670000;660000;670000;660000;620000;610000;630000;640000;640000;630000;610000;</T>
            <T>;600000;610000;610000;600000;580000;570000;550000;520000;520000;520000;520000;540000;530000;540000;540000;520000;510000;500000;500000;500000;</T>
            <T>;500000;490000;470000;450000;440000;430000;470000;540000;530000;510000;510000;500000;500000;510000;500000;490000;480000;460000;440000;440000;</T>
            <T>;480000;480000;480000;490000;500000;480000;470000;460000;460000;450000;470000;450000;450000;470000;480000;480000;470000;450000;460000;460000;</T>
            <T>;480000;470000;490000;490000;480000;470000;470000;470000;500000;490000;470000;</T>
          </X4>
        </X3>
      </X2>
    </X1>
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="2" A3="S" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="2" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="2" A3="E" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'14/06/2018 15:56:18'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;684761,905&quot;;EMG_MAXLEUVEN=&quot;0623,000&quot;;EMG_MAXV=&quot;2730000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0001,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0002,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806180845,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="684761.904761905" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="72960.8282207082" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="623" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 2606055" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="696945.604166667" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'14/06/2018 15:56:18'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;696945,604&quot;;EMG_MAXGENT=&quot;0624,000&quot;;EMG_MAXV=&quot;2606055,000&quot;;EMG_AMPL=&quot;1909109,396&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;0066,000&quot;;EMG_L3XRL=&quot;0065,000&quot;;EMG_L3XDIF=&quot;0051,000&quot;;DATEMARKER#G=&quot;1806180845,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="624" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="2090836.8125" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="616" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="615" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="601" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="1909109.39583333" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="66" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="65" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="51" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=72960.8282207082" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=696945.604166667" A3="U" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1000" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=999;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;124;124;125;121;118;113;108;104;104;108;107;103;97;92;89;90;96;100;102;110;</T>
            <T>;116;113;123;129;128;126;121;116;111;106;104;101;98;97;99;97;94;90;90;89;</T>
            <T>;91;95;98;95;93;91;92;98;98;94;91;89;86;82;82;81;79;76;74;71;</T>
            <T>;68;65;67;72;69;66;66;65;65;65;65;67;63;63;65;66;67;65;67;65;</T>
            <T>;64;60;61;62;63;62;61;58;57;57;56;57;56;59;60;60;59;58;56;55;</T>
            <T>;54;53;55;55;54;58;60;59;59;60;62;66;67;68;70;68;70;69;68;66;</T>
            <T>;66;67;71;74;72;73;74;77;75;74;71;71;75;74;77;77;76;79;82;88;</T>
            <T>;93;91;95;100;101;104;103;103;102;99;95;92;88;84;81;86;89;86;83;79;</T>