<?xml version="1.0"?>
<!DOCTYPE XML[
<!ELEMENT XML (X0*,T*)>
<!ELEMENT X0 (X1*,T*)>
<!ELEMENT X1 (X2*,T*)>
<!ELEMENT X2 (X3*,T*)>
<!ELEMENT X3 (X4*,T*)>
<!ELEMENT X4 (X5*,T*)>
<!ELEMENT X5 (X6*,T*)>
<!ELEMENT X6 (X7*,T*)>
<!ELEMENT X7 (X8*,T*)>
<!ELEMENT X8 (X9*,T*)>
<!ELEMENT X9 (EMPTY)>
<!ELEMENT T (#PCDATA)>
<!ATTLIST X0 A0 CDATA #IMPLIED>
<!ATTLIST X0 A1 CDATA #IMPLIED>
<!ATTLIST X0 A2 CDATA #IMPLIED>
<!ATTLIST X0 A3 CDATA #IMPLIED>
<!ATTLIST X0 A4 CDATA #IMPLIED>
<!ATTLIST X0 A5 CDATA #IMPLIED>
<!ATTLIST X0 A6 CDATA #IMPLIED>
<!ATTLIST X0 A7 CDATA #IMPLIED>
<!ATTLIST X0 A8 CDATA #IMPLIED>
<!ATTLIST X0 A9 CDATA #IMPLIED>
<!ATTLIST X1 A0 CDATA #IMPLIED>
<!ATTLIST X1 A1 CDATA #IMPLIED>
<!ATTLIST X1 A2 CDATA #IMPLIED>
<!ATTLIST X1 A3 CDATA #IMPLIED>
<!ATTLIST X1 A4 CDATA #IMPLIED>
<!ATTLIST X1 A5 CDATA #IMPLIED>
<!ATTLIST X1 A6 CDATA #IMPLIED>
<!ATTLIST X1 A7 CDATA #IMPLIED>
<!ATTLIST X1 A8 CDATA #IMPLIED>
<!ATTLIST X1 A9 CDATA #IMPLIED>
<!ATTLIST X2 A0 CDATA #IMPLIED>
<!ATTLIST X2 A1 CDATA #IMPLIED>
<!ATTLIST X2 A2 CDATA #IMPLIED>
<!ATTLIST X2 A3 CDATA #IMPLIED>
<!ATTLIST X2 A4 CDATA #IMPLIED>
<!ATTLIST X2 A5 CDATA #IMPLIED>
<!ATTLIST X2 A6 CDATA #IMPLIED>
<!ATTLIST X2 A7 CDATA #IMPLIED>
<!ATTLIST X2 A8 CDATA #IMPLIED>
<!ATTLIST X2 A9 CDATA #IMPLIED>
<!ATTLIST X3 A0 CDATA #IMPLIED>
<!ATTLIST X3 A1 CDATA #IMPLIED>
<!ATTLIST X3 A2 CDATA #IMPLIED>
<!ATTLIST X3 A3 CDATA #IMPLIED>
<!ATTLIST X3 A4 CDATA #IMPLIED>
<!ATTLIST X3 A5 CDATA #IMPLIED>
<!ATTLIST X3 A6 CDATA #IMPLIED>
<!ATTLIST X3 A7 CDATA #IMPLIED>
<!ATTLIST X3 A8 CDATA #IMPLIED>
<!ATTLIST X3 A9 CDATA #IMPLIED>
<!ATTLIST X4 A0 CDATA #IMPLIED>
<!ATTLIST X4 A1 CDATA #IMPLIED>
<!ATTLIST X4 A2 CDATA #IMPLIED>
<!ATTLIST X4 A3 CDATA #IMPLIED>
<!ATTLIST X4 A4 CDATA #IMPLIED>
<!ATTLIST X4 A5 CDATA #IMPLIED>
<!ATTLIST X4 A6 CDATA #IMPLIED>
<!ATTLIST X4 A7 CDATA #IMPLIED>
<!ATTLIST X4 A8 CDATA #IMPLIED>
<!ATTLIST X4 A9 CDATA #IMPLIED>
<!ATTLIST X5 A0 CDATA #IMPLIED>
<!ATTLIST X5 A1 CDATA #IMPLIED>
<!ATTLIST X5 A2 CDATA #IMPLIED>
<!ATTLIST X5 A3 CDATA #IMPLIED>
<!ATTLIST X5 A4 CDATA #IMPLIED>
<!ATTLIST X5 A5 CDATA #IMPLIED>
<!ATTLIST X5 A6 CDATA #IMPLIED>
<!ATTLIST X5 A7 CDATA #IMPLIED>
<!ATTLIST X5 A8 CDATA #IMPLIED>
<!ATTLIST X5 A9 CDATA #IMPLIED>
<!ATTLIST X6 A0 CDATA #IMPLIED>
<!ATTLIST X6 A1 CDATA #IMPLIED>
<!ATTLIST X6 A2 CDATA #IMPLIED>
<!ATTLIST X6 A3 CDATA #IMPLIED>
<!ATTLIST X6 A4 CDATA #IMPLIED>
<!ATTLIST X6 A5 CDATA #IMPLIED>
<!ATTLIST X6 A6 CDATA #IMPLIED>
<!ATTLIST X6 A7 CDATA #IMPLIED>
<!ATTLIST X6 A8 CDATA #IMPLIED>
<!ATTLIST X6 A9 CDATA #IMPLIED>
<!ATTLIST X7 A0 CDATA #IMPLIED>
<!ATTLIST X7 A1 CDATA #IMPLIED>
<!ATTLIST X7 A2 CDATA #IMPLIED>
<!ATTLIST X7 A3 CDATA #IMPLIED>
<!ATTLIST X7 A4 CDATA #IMPLIED>
<!ATTLIST X7 A5 CDATA #IMPLIED>
<!ATTLIST X7 A6 CDATA #IMPLIED>
<!ATTLIST X7 A7 CDATA #IMPLIED>
<!ATTLIST X7 A8 CDATA #IMPLIED>
<!ATTLIST X7 A9 CDATA #IMPLIED>
<!ATTLIST X8 A0 CDATA #IMPLIED>
<!ATTLIST X8 A1 CDATA #IMPLIED>
<!ATTLIST X8 A2 CDATA #IMPLIED>
<!ATTLIST X8 A3 CDATA #IMPLIED>
<!ATTLIST X8 A4 CDATA #IMPLIED>
<!ATTLIST X8 A5 CDATA #IMPLIED>
<!ATTLIST X8 A6 CDATA #IMPLIED>
<!ATTLIST X8 A7 CDATA #IMPLIED>
<!ATTLIST X8 A8 CDATA #IMPLIED>
<!ATTLIST X8 A9 CDATA #IMPLIED>
<!ATTLIST X9 A0 CDATA #IMPLIED>
<!ATTLIST X9 A1 CDATA #IMPLIED>
<!ATTLIST X9 A2 CDATA #IMPLIED>
<!ATTLIST X9 A3 CDATA #IMPLIED>
<!ATTLIST X9 A4 CDATA #IMPLIED>
<!ATTLIST X9 A5 CDATA #IMPLIED>
<!ATTLIST X9 A6 CDATA #IMPLIED>
<!ATTLIST X9 A7 CDATA #IMPLIED>
<!ATTLIST X9 A8 CDATA #IMPLIED>
<!ATTLIST X9 A9 CDATA #IMPLIED>
]>
<XML>
  <X0 A0="COMMENT">
    <T>P=PARAMETER;PS=PARAMETERS;T=TRIAL;TS=TRIALS;TPS=TRIALPARAMTERS;
	DP=DATAPOINT;DPS=DATAPOINTS;DPPS=DATAPOINTSPARAMETERS
	PARAMETER:
	N=NAME;P=protection code : U=USER;E=EXPERIMENT
	T=TYPE
	D = extra tag data dictionary</T>
  </X0>
  <X0 A0="PS">
    <X1 A0="P" A1="UPDCREATED" A2="UPD040907" A3="E" />
    <X1 A0="P" A1="IMPORTFILEDATA" A2="14/06/2018 15:42:28" A3="S" />
    <X1 A0="P" A1="FILENAME" A2="14/06/2018 15:42:28" A3="S" />
    <X1 A0="P" A1="EXP:DATATYPE" A2="LEUVEN2007:data" A3="E" />
    <X1 A0="P" A1="VOLFLOW" A2="T" A3="E" />
    <X1 A0="P" A1="FROMAFFECT" A2="T" A3="E" />
    <X1 A0="P" A1="PNEUMOSCRIPT" A2="" A3="E" />
    <X1 A0="P" A1="CH7:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="CH8:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="MAXSAMPLES" A2="154504" A3="E" />
    <X1 A0="P" A1="PROFILE" A2="LEUVEN2007" A3="E" />
    <X1 A0="P" A1="PHUID" A2="5048" A3="U" />
    <X1 A0="P" A1="CH2DISPLAY" A2="DisplayON=T;MyName=CH8;DType=12;Upper=9980000;Lower=110000;Persistent=T;;DType=12;MyName=W1;Upper=8946472;Persistent=T;Lower=-18144.07;;MyName=W2;DType=12;Upper=0;Persistent=T;Lower=0;;DType=12;MyName=W3;Upper=9980000;Persistent=T;Lower=110000;;DType=12;MyName=CH7;Upper=998;Lower=11;Persistent=T;;DType=1;MyName=X;Upper=1025;Lower=0;Persistent=T" A3="U" />
    <X1 A0="P" A1="SHOWSTRIPEMODE" A2="ALL" A3="U" />
    <X1 A0="P" A1="CURRENTCH" A2="CH8" A3="U" />
    <X1 A0="P" A1="DATEMARKER" A2="1806141543" A3="U" />
    <X1 A0="P" A1="HIDEMARKERS" A2="" A3="U" />
    <X1 A0="P" A1="OUT_CH8BIS" A2="OUTPUTEXT=&quot;.EMGBIS.CSV&quot;;DISPLAYWITH=&quot;CH7&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_MEAN=&quot;MEAN&quot;;EMG_MAXGENT=&quot;MAXGENT&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_AMPL=&quot;AMPLITUDO&quot;;EMG_LMAX=&quot;LATENCYMAX&quot;;EMG_L3XLR=&quot;LATNCY3XLR&quot;;EMG_L3XRL=&quot;LATNCY3XRL&quot;;EMG_L3XDIF=&quot;LATNCY3XDIF&quot;;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SPECIALGROUP" A2="" A3="U" />
    <X1 A0="P" A1="EMG:SENS100" A2="100" A3="U" />
    <X1 A0="P" A1="EMG:SENS1000" A2="1000" A3="U" />
    <X1 A0="P" A1="EMG:SENS5000" A2="5000" A3="U" />
    <X1 A0="P" A1="EMG:SENS10000" A2="10000" A3="U" />
    <X1 A0="P" A1="EMG:SENS50000" A2="50000" A3="U" />
    <X1 A0="P" A1="OUT_CH8" A2="OUTPUTEXT=&quot;.EMG.CSV&quot;;DISPLAYWITH=&quot;CH8&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_BL=&quot;BASELINE&quot;;EMG_MAXLEUVEN=&quot;MAXLEUVEN&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_REJECT=&quot;REJECT&quot;;EMG_NON_RESPONS=&quot;NON_RESPPONS&quot;;CH8:PAS:Stimulus#G=Stimulus;CH8:PAS:Total_Trial_Nr#G=Total_Trial_Nr;CH8:PAS:practice#G=practice;CH8:PAS:acq#G=acq;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SRCFILEINFO" A2="" A3="U" />
  </X0>
  <X0 A0="iLOG" />
  <X0 A0="TS">
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="1" A3="S" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="1" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
        <X3 A0="P" A1="CH7REPOTR" A2="" A3="U" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'14/06/2018 15:42:28'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;204761,905&quot;;EMG_MAXLEUVEN=&quot;0725,000&quot;;EMG_MAXV=&quot;790000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0000,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0001,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806141543,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="204761.904761905" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="16619.9923771539" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="725" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 328138.1" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="203525.479910714" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'14/06/2018 15:42:28'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;203525,480&quot;;EMG_MAXGENT=&quot;0647,000&quot;;EMG_MAXV=&quot;328138,100&quot;;EMG_AMPL=&quot;124612,620&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;9999,000&quot;;EMG_L3XRL=&quot;9999,000&quot;;EMG_L3XDIF=&quot;9999,000&quot;;DATEMARKER#G=&quot;1806141543,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="647" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="610576.439732142" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="124612.620089286" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=16619.9923771539" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=203525.479910714" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1062" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=62" A2="S=OK;V=500;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1061;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;30;30;31;30;29;29;28;27;27;25;26;27;25;25;24;24;24;25;26;27;</T>
            <T>;25;24;24;24;26;25;24;24;24;23;24;25;24;24;24;22;22;25;24;25;</T>
            <T>;23;22;22;23;24;23;23;24;22;23;23;23;25;26;25;26;26;27;27;29;</T>
            <T>;29;30;33;38;40;39;39;37;38;38;40;39;42;45;49;54;57;60;66;73;</T>
            <T>;81;89;95;100;104;106;108;111;115;117;119;118;117;116;117;118;116;113;110;106;</T>
            <T>;100;97;94;92;90;89;90;92;93;95;99;102;105;110;114;117;120;123;127;130;</T>
            <T>;131;133;134;135;138;137;137;137;137;136;139;139;139;137;135;133;130;128;125;124;</T>
            <T>;120;113;109;108;106;104;103;100;97;96;95;92;89;87;84;81;79;76;74;73;</T>
            <T>;68;65;64;63;62;62;61;59;57;54;56;55;54;53;51;49;48;47;46;44;</T>
            <T>;42;40;40;39;39;39;37;36;37;36;37;36;34;33;33;32;32;31;31;31;</T>
            <T>;29;27;27;27;27;26;29;29;30;30;32;32;31;30;30;30;30;32;33;33;</T>
            <T>;33;31;31;31;30;29;29;29;29;28;29;29;29;28;29;31;32;31;32;31;</T>
            <T>;29;28;27;30;29;29;29;30;29;29;30;30;31;30;29;29;30;29;29;32;</T>
            <T>;32;32;32;32;32;31;30;29;28;29;31;31;33;34;34;34;34;34;35;35;</T>
            <T>;38;37;37;39;39;41;43;43;48;51;51;50;49;49;46;45;44;43;43;44;</T>
            <T>;42;40;39;38;38;37;37;37;36;36;38;41;44;44;44;43;42;43;45;47;</T>
            <T>;49;53;55;56;55;55;58;64;68;71;74;73;72;70;69;70;70;71;72;72;</T>
            <T>;67;64;62;59;58;56;54;52;53;53;57;59;61;63;65;68;68;68;67;67;</T>
            <T>;68;69;70;71;70;70;71;71;71;69;70;69;69;67;66;63;62;61;61;61;</T>
            <T>;61;60;59;58;57;57;58;56;54;52;51;50;48;46;45;43;43;42;41;41;</T>
            <T>;39;37;37;37;36;36;36;34;34;33;34;34;33;32;31;31;30;29;29;29;</T>
            <T>;27;26;26;25;26;26;25;24;24;25;25;26;26;26;25;27;25;25;27;25;</T>
            <T>;24;24;25;24;24;23;23;23;23;24;25;26;26;25;24;23;23;23;24;25;</T>
            <T>;24;22;22;22;23;22;22;23;21;21;22;23;22;22;21;21;20;21;22;22;</T>
            <T>;21;20;20;21;23;24;23;23;22;21;22;23;22;22;21;21;21;20;20;21;</T>
            <T>;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;</T>
            <T>;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;</T>
            <T>;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;</T>
            <T>;20;20;20;20;21;21;21;21;21;21;24;26;26;27;27;26;27;26;25;25;</T>
            <T>;25;26;27;30;31;31;31;31;31;31;31;29;30;33;31;30;30;29;29;30;</T>
            <T>;31;31;30;28;28;29;30;30;29;28;28;28;29;32;31;31;32;31;30;31;</T>
            <T>;29;30;29;27;27;27;26;27;30;29;29;29;30;30;29;28;28;28;31;31;</T>
            <T>;30;32;31;31;31;30;31;31;30;29;29;29;28;28;28;27;27;27;26;26;</T>
            <T>;26;26;24;23;22;22;23;24;24;25;24;24;24;26;25;25;24;25;24;23;</T>
            <T>;24;24;22;22;22;23;24;24;25;26;25;24;24;24;23;23;23;23;24;23;</T>
            <T>;23;23;22;20;22;23;24;24;25;26;25;27;33;38;37;37;38;43;45;43;</T>
            <T>;42;42;39;44;59;79;82;92;109;115;113;136;142;147;155;155;170;186;191;186;</T>
            <T>;182;201;206;249;286;297;290;286;292;302;330;340;360;369;361;351;339;326;314;301;</T>
            <T>;288;277;264;252;241;231;222;214;210;206;201;193;187;186;181;176;174;173;171;169;</T>
            <T>;164;165;173;182;192;201;205;204;197;189;181;180;181;192;211;218;216;227;227;278;</T>
            <T>;333;362;416;414;438;444;434;432;428;412;394;382;388;384;423;483;513;509;510;520;</T>
            <T>;518;522;521;506;487;476;470;469;470;464;457;449;441;434;421;409;401;392;378;363;</T>
            <T>;347;334;321;305;292;281;271;259;249;237;229;224;222;218;213;209;203;197;193;189;</T>
            <T>;186;185;182;179;177;176;176;172;170;172;171;170;170;167;165;162;158;153;148;142;</T>
            <T>;139;136;131;125;123;123;121;119;117;112;107;105;102;102;100;100;99;97;94;90;</T>
            <T>;89;90;91;89;94;93;98;108;116;121;121;118;116;114;110;108;104;102;100;101;</T>
            <T>;104;107;106;103;100;96;93;95;102;106;111;113;113;113;109;105;105;106;105;104;</T>
            <T>;109;110;125;152;154;181;206;206;201;200;192;191;186;181;176;171;166;168;224;282;</T>
            <T>;313;383;401;389;373;359;347;336;326;314;302;292;282;274;264;251;240;229;219;209;</T>
            <T>;201;198;190;189;198;194;198;203;209;208;201;193;186;182;176;168;161;155;149;143;</T>
            <T>;140;136;131;125;120;116;112;108;104;100;95;91;87;86;83;80;77;75;72;69;</T>
            <T>;68;67;66;63;61;60;59;56;55;60;61;59;58;67;70;70;75;80;80;78;</T>
            <T>;76;73;70;67;67;65;63;64;64;63;61;58;56;55;53;52;55;56;58;58;</T>
            <T>;56;55;</T>
          </X4>
        </X3>
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH8" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1062" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="#OK" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=62" A2="S=OK;V=500;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="MIN" A2="A=185644.25;S=OK;V=559;C=8421376;PHUID=PH1152;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=315625.09;S=OK;V=597;C=16711935;PHUID=PH1147;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=278691.44;S=OK;V=610;C=8421376;PHUID=PH1153;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=309146.75;S=OK;V=621;C=16711935;PHUID=PH1148;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=267454.03;S=OK;V=634;C=8421376;PHUID=PH1154;E=0" A3="U" />
            <X5 A0="M" A1="MAXGENT" A2="TCOLOR=16711935;A=0;S=OK;V=647;C=16711935;PHUID=PH1158;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="C=16711935;E=0;SHM=ON;V=647;PHUID=PH1149;S=HIDE;A=328138.09" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=218231.34;S=OK;V=662;C=8421376;PHUID=PH1155;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=270911.22;S=OK;V=674;C=16711935;PHUID=PH1150;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=201950.77;S=OK;V=686;C=8421376;PHUID=PH1156;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=273734.5;S=OK;V=698;C=16711935;PHUID=PH1151;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=211598.83;S=OK;V=709;C=8421376;PHUID=PH1157;E=0" A3="U" />
            <X5 A0="M" A1="MAXLEUVEN" A2="TCOLOR=65280;A=0;S=OK;V=725;C=65280;PHUID=PH1159;E=0" A3="U" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1061;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;300000;300000;310000;300000;290000;290000;280000;270000;270000;250000;260000;270000;250000;250000;240000;240000;240000;250000;260000;270000;</T>
            <T>;250000;240000;240000;240000;260000;250000;240000;240000;240000;230000;240000;250000;240000;240000;240000;220000;220000;250000;240000;250000;</T>
            <T>;230000;220000;220000;230000;240000;230000;230000;240000;220000;230000;230000;230000;250000;260000;250000;260000;260000;270000;270000;290000;</T>
            <T>;290000;300000;330000;380000;400000;390000;390000;370000;380000;380000;400000;390000;420000;450000;490000;540000;570000;600000;660000;730000;</T>
            <T>;810000;890000;950000;1000000;1040000;1060000;1080000;1110000;1150000;1170000;1190000;1180000;1170000;1160000;1170000;1180000;1160000;1130000;1100000;1060000;</T>
            <T>;1000000;970000;940000;920000;900000;890000;900000;920000;930000;950000;990000;1020000;1050000;1100000;1140000;1170000;1200000;1230000;1270000;1300000;</T>
            <T>;1310000;1330000;1340000;1350000;1380000;1370000;1370000;1370000;1370000;1360000;1390000;1390000;1390000;1370000;1350000;1330000;1300000;1280000;1250000;1240000;</T>
            <T>;1200000;1130000;1090000;1080000;1060000;1040000;1030000;1000000;970000;960000;950000;920000;890000;870000;840000;810000;790000;760000;740000;730000;</T>
            <T>;680000;650000;640000;630000;620000;620000;610000;590000;570000;540000;560000;550000;540000;530000;510000;490000;480000;470000;460000;440000;</T>
            <T>;420000;400000;400000;390000;390000;390000;370000;360000;370000;360000;370000;360000;340000;330000;330000;320000;320000;310000;310000;310000;</T>
            <T>;290000;270000;270000;270000;270000;260000;290000;290000;300000;300000;320000;320000;310000;300000;300000;300000;300000;320000;330000;330000;</T>
            <T>;330000;310000;310000;310000;300000;290000;290000;290000;290000;280000;290000;290000;290000;280000;290000;310000;320000;310000;320000;310000;</T>
            <T>;290000;280000;270000;300000;290000;290000;290000;300000;290000;290000;300000;300000;310000;300000;290000;290000;300000;290000;290000;320000;</T>
            <T>;320000;320000;320000;320000;320000;310000;300000;290000;280000;290000;310000;310000;330000;340000;340000;340000;340000;340000;350000;350000;</T>
            <T>;380000;370000;370000;390000;390000;410000;430000;430000;480000;510000;510000;500000;490000;490000;460000;450000;440000;430000;430000;440000;</T>
            <T>;420000;400000;390000;380000;380000;370000;370000;370000;360000;360000;380000;410000;440000;440000;440000;430000;420000;430000;450000;470000;</T>
            <T>;490000;530000;550000;560000;550000;550000;580000;640000;680000;710000;740000;730000;720000;700000;690000;700000;700000;710000;720000;720000;</T>
            <T>;670000;640000;620000;590000;580000;560000;540000;520000;530000;530000;570000;590000;610000;630000;650000;680000;680000;680000;670000;670000;</T>
            <T>;680000;690000;700000;710000;700000;700000;710000;710000;710000;690000;700000;690000;690000;670000;660000;630000;620000;610000;610000;610000;</T>
            <T>;610000;600000;590000;580000;570000;570000;580000;560000;540000;520000;510000;500000;480000;460000;450000;430000;430000;420000;410000;410000;</T>
            <T>;390000;370000;370000;370000;360000;360000;360000;340000;340000;330000;340000;340000;330000;320000;310000;310000;300000;290000;290000;290000;</T>
            <T>;270000;260000;260000;250000;260000;260000;250000;240000;240000;250000;250000;260000;260000;260000;250000;270000;250000;250000;270000;250000;</T>
            <T>;240000;240000;250000;240000;240000;230000;230000;230000;230000;240000;250000;260000;260000;250000;240000;230000;230000;230000;240000;250000;</T>
            <T>;240000;220000;220000;220000;230000;220000;220000;230000;210000;210000;220000;230000;220000;220000;210000;210000;200000;210000;220000;220000;</T>
            <T>;210000;200000;200000;210000;230000;240000;230000;230000;220000;210000;220000;230000;220000;220000;210000;210000;210000;200000;200000;210000;</T>
            <T>;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;</T>
            <T>;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;</T>
            <T>;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;</T>
            <T>;200000;200000;200000;200000;210000;210000;210000;210000;210000;210000;240000;260000;260000;270000;270000;260000;270000;260000;250000;250000;</T>
            <T>;250000;260000;270000;300000;310000;310000;310000;310000;310000;310000;310000;290000;300000;330000;310000;300000;300000;290000;290000;300000;</T>
            <T>;310000;310000;300000;280000;280000;290000;300000;300000;290000;280000;280000;280000;290000;320000;310000;310000;320000;310000;300000;310000;</T>
            <T>;290000;300000;290000;270000;270000;270000;260000;270000;300000;290000;290000;290000;300000;300000;290000;280000;280000;280000;310000;310000;</T>
            <T>;300000;320000;310000;310000;310000;300000;310000;310000;300000;290000;290000;290000;280000;280000;280000;270000;270000;270000;260000;260000;</T>
            <T>;260000;260000;240000;230000;220000;220000;230000;240000;240000;250000;240000;240000;240000;260000;250000;250000;240000;250000;240000;230000;</T>
            <T>;240000;240000;220000;220000;220000;230000;240000;240000;250000;260000;250000;240000;240000;240000;230000;230000;230000;230000;240000;230000;</T>
            <T>;230000;230000;220000;200000;220000;230000;240000;240000;250000;260000;250000;270000;330000;380000;370000;370000;380000;430000;450000;430000;</T>
            <T>;420000;420000;390000;440000;590000;790000;820000;920000;1090000;1150000;1130000;1360000;1420000;1470000;1550000;1550000;1700000;1860000;1910000;1860000;</T>
            <T>;1820000;2010000;2060000;2490000;2860000;2970000;2900000;2860000;2920000;3020000;3300000;3400000;3600000;3690000;3610000;3510000;3390000;3260000;3140000;3010000;</T>
            <T>;2880000;2770000;2640000;2520000;2410000;2310000;2220000;2140000;2100000;2060000;2010000;1930000;1870000;1860000;1810000;1760000;1740000;1730000;1710000;1690000;</T>
            <T>;1640000;1650000;1730000;1820000;1920000;2010000;2050000;2040000;1970000;1890000;1810000;1800000;1810000;1920000;2110000;2180000;2160000;2270000;2270000;2780000;</T>
            <T>;3330000;3620000;4160000;4140000;4380000;4440000;4340000;4320000;4280000;4120000;3940000;3820000;3880000;3840000;4230000;4830000;5130000;5090000;5100000;5200000;</T>
            <T>;5180000;5220000;5210000;5060000;4870000;4760000;4700000;4690000;4700000;4640000;4570000;4490000;4410000;4340000;4210000;4090000;4010000;3920000;3780000;3630000;</T>
            <T>;3470000;3340000;3210000;3050000;2920000;2810000;2710000;2590000;2490000;2370000;2290000;2240000;2220000;2180000;2130000;2090000;2030000;1970000;1930000;1890000;</T>
            <T>;1860000;1850000;1820000;1790000;1770000;1760000;1760000;1720000;1700000;1720000;1710000;1700000;1700000;1670000;1650000;1620000;1580000;1530000;1480000;1420000;</T>
            <T>;1390000;1360000;1310000;1250000;1230000;1230000;1210000;1190000;1170000;1120000;1070000;1050000;1020000;1020000;1000000;1000000;990000;970000;940000;900000;</T>
            <T>;890000;900000;910000;890000;940000;930000;980000;1080000;1160000;1210000;1210000;1180000;1160000;1140000;1100000;1080000;1040000;1020000;1000000;1010000;</T>
            <T>;1040000;1070000;1060000;1030000;1000000;960000;930000;950000;1020000;1060000;1110000;1130000;1130000;1130000;1090000;1050000;1050000;1060000;1050000;1040000;</T>
            <T>;1090000;1100000;1250000;1520000;1540000;1810000;2060000;2060000;2010000;2000000;1920000;1910000;1860000;1810000;1760000;1710000;1660000;1680000;2240000;2820000;</T>
            <T>;3130000;3830000;4010000;3890000;3730000;3590000;3470000;3360000;3260000;3140000;3020000;2920000;2820000;2740000;2640000;2510000;2400000;2290000;2190000;2090000;</T>
            <T>;2010000;1980000;1900000;1890000;1980000;1940000;1980000;2030000;2090000;2080000;2010000;1930000;1860000;1820000;1760000;1680000;1610000;1550000;1490000;1430000;</T>
            <T>;1400000;1360000;1310000;1250000;1200000;1160000;1120000;1080000;1040000;1000000;950000;910000;870000;860000;830000;800000;770000;750000;720000;690000;</T>
            <T>;680000;670000;660000;630000;610000;600000;590000;560000;550000;600000;610000;590000;580000;670000;700000;700000;750000;800000;800000;780000;</T>
            <T>;760000;730000;700000;670000;670000;650000;630000;640000;640000;630000;610000;580000;560000;550000;530000;520000;550000;560000;580000;580000;</T>
            <T>;560000;550000;</T>
          </X4>
        </X3>
      </X2>
    </X1>
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="2" A3="S" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="2" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="2" A3="E" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'14/06/2018 15:42:28'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;170952,381&quot;;EMG_MAXLEUVEN=&quot;0649,000&quot;;EMG_MAXV=&quot;1130000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0010,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0002,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806141543,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="170952.380952381" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="13631.3705709251" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="649" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 1056002" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="172867.665178571" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'14/06/2018 15:42:28'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;172867,665&quot;;EMG_MAXGENT=&quot;0653,000&quot;;EMG_MAXV=&quot;1056002,000&quot;;EMG_AMPL=&quot;883134,335&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;0068,000&quot;;EMG_L3XRL=&quot;0067,000&quot;;EMG_L3XDIF=&quot;0050,000&quot;;DATEMARKER#G=&quot;1806141543,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="653" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="518602.995535713" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="618" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="617" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="600" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="883134.334821429" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="68" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="67" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="50" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=13631.3705709251" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=172867.665178571" A3="U" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1024" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=10" A2="S=OK;V=422;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=452;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=2" A2="S=OK;V=475;C=255;E=" A3="E" />