<?xml version="1.0"?>
<!DOCTYPE XML[
<!ELEMENT XML (X0*,T*)>
<!ELEMENT X0 (X1*,T*)>
<!ELEMENT X1 (X2*,T*)>
<!ELEMENT X2 (X3*,T*)>
<!ELEMENT X3 (X4*,T*)>
<!ELEMENT X4 (X5*,T*)>
<!ELEMENT X5 (X6*,T*)>
<!ELEMENT X6 (X7*,T*)>
<!ELEMENT X7 (X8*,T*)>
<!ELEMENT X8 (X9*,T*)>
<!ELEMENT X9 (EMPTY)>
<!ELEMENT T (#PCDATA)>
<!ATTLIST X0 A0 CDATA #IMPLIED>
<!ATTLIST X0 A1 CDATA #IMPLIED>
<!ATTLIST X0 A2 CDATA #IMPLIED>
<!ATTLIST X0 A3 CDATA #IMPLIED>
<!ATTLIST X0 A4 CDATA #IMPLIED>
<!ATTLIST X0 A5 CDATA #IMPLIED>
<!ATTLIST X0 A6 CDATA #IMPLIED>
<!ATTLIST X0 A7 CDATA #IMPLIED>
<!ATTLIST X0 A8 CDATA #IMPLIED>
<!ATTLIST X0 A9 CDATA #IMPLIED>
<!ATTLIST X1 A0 CDATA #IMPLIED>
<!ATTLIST X1 A1 CDATA #IMPLIED>
<!ATTLIST X1 A2 CDATA #IMPLIED>
<!ATTLIST X1 A3 CDATA #IMPLIED>
<!ATTLIST X1 A4 CDATA #IMPLIED>
<!ATTLIST X1 A5 CDATA #IMPLIED>
<!ATTLIST X1 A6 CDATA #IMPLIED>
<!ATTLIST X1 A7 CDATA #IMPLIED>
<!ATTLIST X1 A8 CDATA #IMPLIED>
<!ATTLIST X1 A9 CDATA #IMPLIED>
<!ATTLIST X2 A0 CDATA #IMPLIED>
<!ATTLIST X2 A1 CDATA #IMPLIED>
<!ATTLIST X2 A2 CDATA #IMPLIED>
<!ATTLIST X2 A3 CDATA #IMPLIED>
<!ATTLIST X2 A4 CDATA #IMPLIED>
<!ATTLIST X2 A5 CDATA #IMPLIED>
<!ATTLIST X2 A6 CDATA #IMPLIED>
<!ATTLIST X2 A7 CDATA #IMPLIED>
<!ATTLIST X2 A8 CDATA #IMPLIED>
<!ATTLIST X2 A9 CDATA #IMPLIED>
<!ATTLIST X3 A0 CDATA #IMPLIED>
<!ATTLIST X3 A1 CDATA #IMPLIED>
<!ATTLIST X3 A2 CDATA #IMPLIED>
<!ATTLIST X3 A3 CDATA #IMPLIED>
<!ATTLIST X3 A4 CDATA #IMPLIED>
<!ATTLIST X3 A5 CDATA #IMPLIED>
<!ATTLIST X3 A6 CDATA #IMPLIED>
<!ATTLIST X3 A7 CDATA #IMPLIED>
<!ATTLIST X3 A8 CDATA #IMPLIED>
<!ATTLIST X3 A9 CDATA #IMPLIED>
<!ATTLIST X4 A0 CDATA #IMPLIED>
<!ATTLIST X4 A1 CDATA #IMPLIED>
<!ATTLIST X4 A2 CDATA #IMPLIED>
<!ATTLIST X4 A3 CDATA #IMPLIED>
<!ATTLIST X4 A4 CDATA #IMPLIED>
<!ATTLIST X4 A5 CDATA #IMPLIED>
<!ATTLIST X4 A6 CDATA #IMPLIED>
<!ATTLIST X4 A7 CDATA #IMPLIED>
<!ATTLIST X4 A8 CDATA #IMPLIED>
<!ATTLIST X4 A9 CDATA #IMPLIED>
<!ATTLIST X5 A0 CDATA #IMPLIED>
<!ATTLIST X5 A1 CDATA #IMPLIED>
<!ATTLIST X5 A2 CDATA #IMPLIED>
<!ATTLIST X5 A3 CDATA #IMPLIED>
<!ATTLIST X5 A4 CDATA #IMPLIED>
<!ATTLIST X5 A5 CDATA #IMPLIED>
<!ATTLIST X5 A6 CDATA #IMPLIED>
<!ATTLIST X5 A7 CDATA #IMPLIED>
<!ATTLIST X5 A8 CDATA #IMPLIED>
<!ATTLIST X5 A9 CDATA #IMPLIED>
<!ATTLIST X6 A0 CDATA #IMPLIED>
<!ATTLIST X6 A1 CDATA #IMPLIED>
<!ATTLIST X6 A2 CDATA #IMPLIED>
<!ATTLIST X6 A3 CDATA #IMPLIED>
<!ATTLIST X6 A4 CDATA #IMPLIED>
<!ATTLIST X6 A5 CDATA #IMPLIED>
<!ATTLIST X6 A6 CDATA #IMPLIED>
<!ATTLIST X6 A7 CDATA #IMPLIED>
<!ATTLIST X6 A8 CDATA #IMPLIED>
<!ATTLIST X6 A9 CDATA #IMPLIED>
<!ATTLIST X7 A0 CDATA #IMPLIED>
<!ATTLIST X7 A1 CDATA #IMPLIED>
<!ATTLIST X7 A2 CDATA #IMPLIED>
<!ATTLIST X7 A3 CDATA #IMPLIED>
<!ATTLIST X7 A4 CDATA #IMPLIED>
<!ATTLIST X7 A5 CDATA #IMPLIED>
<!ATTLIST X7 A6 CDATA #IMPLIED>
<!ATTLIST X7 A7 CDATA #IMPLIED>
<!ATTLIST X7 A8 CDATA #IMPLIED>
<!ATTLIST X7 A9 CDATA #IMPLIED>
<!ATTLIST X8 A0 CDATA #IMPLIED>
<!ATTLIST X8 A1 CDATA #IMPLIED>
<!ATTLIST X8 A2 CDATA #IMPLIED>
<!ATTLIST X8 A3 CDATA #IMPLIED>
<!ATTLIST X8 A4 CDATA #IMPLIED>
<!ATTLIST X8 A5 CDATA #IMPLIED>
<!ATTLIST X8 A6 CDATA #IMPLIED>
<!ATTLIST X8 A7 CDATA #IMPLIED>
<!ATTLIST X8 A8 CDATA #IMPLIED>
<!ATTLIST X8 A9 CDATA #IMPLIED>
<!ATTLIST X9 A0 CDATA #IMPLIED>
<!ATTLIST X9 A1 CDATA #IMPLIED>
<!ATTLIST X9 A2 CDATA #IMPLIED>
<!ATTLIST X9 A3 CDATA #IMPLIED>
<!ATTLIST X9 A4 CDATA #IMPLIED>
<!ATTLIST X9 A5 CDATA #IMPLIED>
<!ATTLIST X9 A6 CDATA #IMPLIED>
<!ATTLIST X9 A7 CDATA #IMPLIED>
<!ATTLIST X9 A8 CDATA #IMPLIED>
<!ATTLIST X9 A9 CDATA #IMPLIED>
]>
<XML>
  <X0 A0="COMMENT">
    <T>P=PARAMETER;PS=PARAMETERS;T=TRIAL;TS=TRIALS;TPS=TRIALPARAMTERS;
	DP=DATAPOINT;DPS=DATAPOINTS;DPPS=DATAPOINTSPARAMETERS
	PARAMETER:
	N=NAME;P=protection code : U=USER;E=EXPERIMENT
	T=TYPE
	D = extra tag data dictionary</T>
  </X0>
  <X0 A0="PS">
    <X1 A0="P" A1="UPDCREATED" A2="UPD040907" A3="E" />
    <X1 A0="P" A1="IMPORTFILEDATA" A2="18/06/2018 8:58:46" A3="S" />
    <X1 A0="P" A1="FILENAME" A2="18/06/2018 8:58:46" A3="S" />
    <X1 A0="P" A1="EXP:DATATYPE" A2="LEUVEN2007:data" A3="E" />
    <X1 A0="P" A1="VOLFLOW" A2="T" A3="E" />
    <X1 A0="P" A1="FROMAFFECT" A2="T" A3="E" />
    <X1 A0="P" A1="PNEUMOSCRIPT" A2="" A3="E" />
    <X1 A0="P" A1="CH7:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="CH8:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="MAXSAMPLES" A2="154520" A3="E" />
    <X1 A0="P" A1="PROFILE" A2="LEUVEN2007" A3="E" />
    <X1 A0="P" A1="PHUID" A2="5220" A3="U" />
    <X1 A0="P" A1="CH2DISPLAY" A2="DisplayON=T;MyName=CH8;DType=12;Upper=18370000;Lower=90000;Persistent=T;;DType=12;MyName=W1;Upper=7870997;Persistent=T;Lower=0;;MyName=W2;DType=12;Upper=0;Persistent=T;Lower=0;;DType=12;MyName=W3;Upper=18370000;Persistent=T;Lower=90000;;DType=12;MyName=CH7;Upper=1837;Lower=9;Persistent=T;;DType=1;MyName=X;Upper=1090;Lower=0;Persistent=T" A3="U" />
    <X1 A0="P" A1="SHOWSTRIPEMODE" A2="ALL" A3="U" />
    <X1 A0="P" A1="CURRENTCH" A2="CH8" A3="U" />
    <X1 A0="P" A1="DATEMARKER" A2="1806180859" A3="U" />
    <X1 A0="P" A1="HIDEMARKERS" A2="" A3="U" />
    <X1 A0="P" A1="OUT_CH8BIS" A2="OUTPUTEXT=&quot;.EMGBIS.CSV&quot;;DISPLAYWITH=&quot;CH7&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_MEAN=&quot;MEAN&quot;;EMG_MAXGENT=&quot;MAXGENT&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_AMPL=&quot;AMPLITUDO&quot;;EMG_LMAX=&quot;LATENCYMAX&quot;;EMG_L3XLR=&quot;LATNCY3XLR&quot;;EMG_L3XRL=&quot;LATNCY3XRL&quot;;EMG_L3XDIF=&quot;LATNCY3XDIF&quot;;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SPECIALGROUP" A2="" A3="U" />
    <X1 A0="P" A1="EMG:SENS100" A2="100" A3="U" />
    <X1 A0="P" A1="EMG:SENS1000" A2="1000" A3="U" />
    <X1 A0="P" A1="EMG:SENS5000" A2="5000" A3="U" />
    <X1 A0="P" A1="EMG:SENS10000" A2="10000" A3="U" />
    <X1 A0="P" A1="EMG:SENS50000" A2="50000" A3="U" />
    <X1 A0="P" A1="OUT_CH8" A2="OUTPUTEXT=&quot;.EMG.CSV&quot;;DISPLAYWITH=&quot;CH8&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_BL=&quot;BASELINE&quot;;EMG_MAXLEUVEN=&quot;MAXLEUVEN&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_REJECT=&quot;REJECT&quot;;EMG_NON_RESPONS=&quot;NON_RESPPONS&quot;;CH8:PAS:Stimulus#G=Stimulus;CH8:PAS:Total_Trial_Nr#G=Total_Trial_Nr;CH8:PAS:practice#G=practice;CH8:PAS:acq#G=acq;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SRCFILEINFO" A2="" A3="U" />
  </X0>
  <X0 A0="iLOG" />
  <X0 A0="TS">
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="1" A3="S" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="1" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
        <X3 A0="P" A1="CH7REPOTR" A2="" A3="U" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'18/06/2018 8:58:46'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;148095,238&quot;;EMG_MAXLEUVEN=&quot;0716,000&quot;;EMG_MAXV=&quot;3290000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0010,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0001,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806180859,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="148095.238095238" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="7204.763167192" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="716" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 3217365" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="149298.037946429" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'18/06/2018 8:58:46'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;149298,038&quot;;EMG_MAXGENT=&quot;0722,000&quot;;EMG_MAXV=&quot;3217365,000&quot;;EMG_AMPL=&quot;3068066,962&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;9999,000&quot;;EMG_L3XRL=&quot;9999,000&quot;;EMG_L3XDIF=&quot;0045,000&quot;;DATEMARKER#G=&quot;1806180859,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="722" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="447894.113839287" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="595" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="3068066.96205357" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="45" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=7204.763167192" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=149298.037946429" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1111" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=19" A2="S=OK;V=548;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="CORE=10" A2="S=OK;V=806;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=2" A2="S=OK;V=836;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=858;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=890;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=946;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=2" A2="S=OK;V=961;C=255;E=" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1110;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;19;19;17;17;18;17;17;17;16;17;17;18;20;20;20;19;19;19;18;18;</T>
            <T>;17;18;15;15;15;16;16;15;16;15;15;15;15;17;17;18;17;18;18;19;</T>
            <T>;20;19;19;20;17;17;16;17;16;16;15;15;15;17;16;19;19;18;17;16;</T>
            <T>;16;16;19;20;21;21;20;20;20;20;20;20;20;20;20;20;20;22;22;22;</T>
            <T>;22;21;20;20;20;19;20;22;20;20;20;19;19;19;19;18;18;18;18;20;</T>
            <T>;20;20;20;19;18;19;18;18;17;17;16;16;16;16;16;16;17;16;15;15;</T>
            <T>;17;19;19;19;19;18;17;17;17;16;17;17;15;15;14;15;15;14;14;15;</T>
            <T>;13;13;12;14;14;14;13;12;12;13;12;13;13;15;15;15;14;14;14;14;</T>
            <T>;15;15;14;13;13;14;14;13;13;12;12;11;11;12;12;13;10;10;11;11;</T>
            <T>;11;12;13;13;13;13;15;17;17;18;17;16;15;14;15;16;16;16;14;14;</T>
            <T>;15;16;18;18;19;18;17;18;16;18;18;19;19;18;18;18;18;18;18;19;</T>
            <T>;16;16;16;16;15;15;15;15;13;13;12;13;13;15;15;15;15;15;15;16;</T>
            <T>;16;17;15;15;15;16;16;15;15;15;14;13;12;14;14;14;14;16;15;15;</T>
            <T>;15;16;16;16;16;16;16;17;17;17;17;17;18;19;19;20;20;20;19;20;</T>
            <T>;20;20;19;19;19;19;16;16;17;18;18;19;19;18;18;17;17;18;18;18;</T>
            <T>;18;19;18;18;17;17;19;20;19;19;18;19;19;19;20;20;18;18;18;20;</T>
            <T>;20;20;20;19;19;19;19;20;20;20;19;19;19;18;18;19;20;20;18;18;</T>
            <T>;18;19;19;19;19;18;18;18;17;17;17;18;15;15;15;14;15;14;14;14;</T>
            <T>;12;12;11;13;13;14;14;13;13;14;14;15;16;16;15;15;14;15;16;17;</T>
            <T>;19;20;19;18;18;20;20;20;20;20;22;22;22;22;22;22;20;20;19;19;</T>
            <T>;19;18;19;20;20;21;20;22;22;21;21;21;22;21;21;22;21;21;19;19;</T>
            <T>;18;19;19;19;19;18;17;16;15;17;17;17;16;16;16;17;15;15;16;17;</T>
            <T>;13;13;13;14;14;15;15;14;14;16;15;17;17;17;16;16;16;15;16;15;</T>
            <T>;15;15;12;12;13;13;14;13;13;13;13;13;13;15;15;14;13;14;13;13;</T>
            <T>;13;13;13;14;11;11;12;12;11;11;11;10;11;10;11;13;13;13;13;14;</T>
            <T>;15;16;16;16;16;17;16;16;17;16;16;17;17;17;16;15;17;21;21;21;</T>
            <T>;21;21;22;22;21;22;24;24;22;22;21;21;21;20;20;19;18;17;16;18;</T>
            <T>;18;17;17;16;16;16;14;15;15;15;15;15;15;15;15;15;15;15;15;15;</T>
            <T>;15;15;15;15;15;15;15;15;14;13;14;14;15;16;16;16;15;15;15;16;</T>
            <T>;16;16;15;14;14;13;13;13;14;11;11;11;12;11;10;12;11;10;10;11;</T>
            <T>;12;14;12;13;14;13;15;17;20;20;20;20;20;19;19;20;20;20;20;24;</T>
            <T>;24;23;23;22;23;21;20;21;20;21;19;19;18;20;20;20;21;21;21;20;</T>
            <T>;19;21;21;21;20;19;19;18;19;20;20;20;18;18;19;20;20;20;20;19;</T>
            <T>;18;18;17;19;19;18;17;17;16;16;15;17;16;16;13;13;13;14;13;13;</T>
            <T>;14;13;13;13;13;17;17;25;34;43;55;55;57;57;63;68;96;96;120;122;</T>
            <T>;128;141;148;164;198;215;212;232;232;253;269;288;305;308;301;323;329;325;316;316;</T>
            <T>;304;294;301;316;311;310;324;332;333;328;328;313;300;293;290;289;287;283;278;274;</T>
            <T>;264;264;254;242;232;222;212;204;196;189;180;175;175;168;165;163;160;158;158;159;</T>
            <T>;160;163;162;162;164;166;170;173;175;173;169;166;165;169;169;166;162;159;156;152;</T>
            <T>;148;144;141;137;132;132;129;127;124;118;115;112;107;103;99;97;97;95;92;87;</T>
            <T>;84;80;76;74;71;68;63;63;63;63;63;63;63;63;63;63;63;64;63;60;</T>
            <T>;58;58;57;55;53;54;55;54;55;55;56;57;56;55;53;51;47;47;47;47;</T>
            <T>;45;46;44;45;47;48;49;49;50;50;51;51;49;47;46;46;45;44;42;42;</T>
            <T>;42;42;41;41;40;40;38;37;36;36;38;42;42;41;41;42;43;40;39;38;</T>
            <T>;36;35;32;32;32;31;30;30;29;27;26;26;26;26;24;25;26;26;26;25;</T>
            <T>;25;23;23;22;21;19;19;22;25;28;29;29;30;33;36;38;41;40;38;38;</T>
            <T>;36;35;35;35;34;33;31;30;31;31;31;31;30;30;29;28;28;29;31;29;</T>
            <T>;28;27;26;26;26;25;25;25;25;25;25;23;24;26;26;25;26;25;25;24;</T>
            <T>;23;26;26;26;24;23;24;23;22;23;25;26;26;24;23;23;23;22;22;23;</T>
            <T>;22;22;24;27;26;26;26;25;24;23;23;22;22;19;20;19;19;20;20;21;</T>
            <T>;21;20;20;21;20;20;21;20;19;19;20;20;20;18;19;17;18;17;17;17;</T>
            <T>;17;17;17;19;17;17;17;16;16;15;16;17;18;15;15;16;18;19;21;22;</T>
            <T>;21;21;23;27;28;28;27;26;26;25;26;27;28;26;25;24;24;23;21;23;</T>
            <T>;21;20;20;22;20;20;20;21;21;20;21;20;22;22;21;21;21;20;20;20;</T>
            <T>;20;20;19;19;19;19;19;19;19;19;21;22;24;23;22;22;21;21;21;20;</T>
            <T>;19;18;19;20;20;19;18;18;16;16;17;</T>
          </X4>
        </X3>
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH8" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1111" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="#OK" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=19" A2="S=OK;V=548;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="MAX" A2="A=157999.44;S=OK;V=556;C=16711935;PHUID=PH1221;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=138783.88;S=OK;V=568;C=8421376;PHUID=PH1226;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=159765.67;S=OK;V=579;C=16711935;PHUID=PH1222;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=96775.41;S=OK;V=595;C=8421376;PHUID=PH1227;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=213667.47;S=OK;V=630;C=16711935;PHUID=PH1223;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=185673.47;S=OK;V=645;C=8421376;PHUID=PH1228;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=205340.48;S=OK;V=656;C=16711935;PHUID=PH1224;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=132859.02;S=OK;V=674;C=8421376;PHUID=PH1229;E=0" A3="U" />
            <X5 A0="M" A1="MAXLEUVEN" A2="TCOLOR=65280;A=0;S=OK;V=716;C=65280;PHUID=PH1232;E=0" A3="U" />
            <X5 A0="M" A1="MAXGENT" A2="TCOLOR=16711935;A=0;S=OK;V=722;C=16711935;PHUID=PH1231;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="C=16711935;E=0;SHM=ON;V=722;PHUID=PH1225;S=HIDE;A=3217365.25" A3="U" />
            <X5 A0="M" A1="CORE=10" A2="S=OK;V=806;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=2" A2="S=OK;V=836;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=858;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=890;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=3" A2="S=OK;V=946;C=255;E=" A3="E" />
            <X5 A0="M" A1="CORE=2" A2="S=OK;V=961;C=255;E=" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1110;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;190000;190000;170000;170000;180000;170000;170000;170000;160000;170000;170000;180000;200000;200000;200000;190000;190000;190000;180000;180000;</T>
            <T>;170000;180000;150000;150000;150000;160000;160000;150000;160000;150000;150000;150000;150000;170000;170000;180000;170000;180000;180000;190000;</T>
            <T>;200000;190000;190000;200000;170000;170000;160000;170000;160000;160000;150000;150000;150000;170000;160000;190000;190000;180000;170000;160000;</T>
            <T>;160000;160000;190000;200000;210000;210000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;200000;220000;220000;220000;</T>
            <T>;220000;210000;200000;200000;200000;190000;200000;220000;200000;200000;200000;190000;190000;190000;190000;180000;180000;180000;180000;200000;</T>
            <T>;200000;200000;200000;190000;180000;190000;180000;180000;170000;170000;160000;160000;160000;160000;160000;160000;170000;160000;150000;150000;</T>
            <T>;170000;190000;190000;190000;190000;180000;170000;170000;170000;160000;170000;170000;150000;150000;140000;150000;150000;140000;140000;150000;</T>
            <T>;130000;130000;120000;140000;140000;140000;130000;120000;120000;130000;120000;130000;130000;150000;150000;150000;140000;140000;140000;140000;</T>
            <T>;150000;150000;140000;130000;130000;140000;140000;130000;130000;120000;120000;110000;110000;120000;120000;130000;100000;100000;110000;110000;</T>
            <T>;110000;120000;130000;130000;130000;130000;150000;170000;170000;180000;170000;160000;150000;140000;150000;160000;160000;160000;140000;140000;</T>
            <T>;150000;160000;180000;180000;190000;180000;170000;180000;160000;180000;180000;190000;190000;180000;180000;180000;180000;180000;180000;190000;</T>
            <T>;160000;160000;160000;160000;150000;150000;150000;150000;130000;130000;120000;130000;130000;150000;150000;150000;150000;150000;150000;160000;</T>
            <T>;160000;170000;150000;150000;150000;160000;160000;150000;150000;150000;140000;130000;120000;140000;140000;140000;140000;160000;150000;150000;</T>
            <T>;150000;160000;160000;160000;160000;160000;160000;170000;170000;170000;170000;170000;180000;190000;190000;200000;200000;200000;190000;200000;</T>
            <T>;200000;200000;190000;190000;190000;190000;160000;160000;170000;180000;180000;190000;190000;180000;180000;170000;170000;180000;180000;180000;</T>
            <T>;180000;190000;180000;180000;170000;170000;190000;200000;190000;190000;180000;190000;190000;190000;200000;200000;180000;180000;180000;200000;</T>
            <T>;200000;200000;200000;190000;190000;190000;190000;200000;200000;200000;190000;190000;190000;180000;180000;190000;200000;200000;180000;180000;</T>
            <T>;180000;190000;190000;190000;190000;180000;180000;180000;170000;170000;170000;180000;150000;150000;150000;140000;150000;140000;140000;140000;</T>
            <T>;120000;120000;110000;130000;130000;140000;140000;130000;130000;140000;140000;150000;160000;160000;150000;150000;140000;150000;160000;170000;</T>
            <T>;190000;200000;190000;180000;180000;200000;200000;200000;200000;200000;220000;220000;220000;220000;220000;220000;200000;200000;190000;190000;</T>
            <T>;190000;180000;190000;200000;200000;210000;200000;220000;220000;210000;210000;210000;220000;210000;210000;220000;210000;210000;190000;190000;</T>
            <T>;180000;190000;190000;190000;190000;180000;170000;160000;150000;170000;170000;170000;160000;160000;160000;170000;150000;150000;160000;170000;</T>
            <T>;130000;130000;130000;140000;140000;150000;150000;140000;140000;160000;150000;170000;170000;170000;160000;160000;160000;150000;160000;150000;</T>
            <T>;150000;150000;120000;120000;130000;130000;140000;130000;130000;130000;130000;130000;130000;150000;150000;140000;130000;140000;130000;130000;</T>
            <T>;130000;130000;130000;140000;110000;110000;120000;120000;110000;110000;110000;100000;110000;100000;110000;130000;130000;130000;130000;140000;</T>
            <T>;150000;160000;160000;160000;160000;170000;160000;160000;170000;160000;160000;170000;170000;170000;160000;150000;170000;210000;210000;210000;</T>
            <T>;210000;210000;220000;220000;210000;220000;240000;240000;220000;220000;210000;210000;210000;200000;200000;190000;180000;170000;160000;180000;</T>
            <T>;180000;170000;170000;160000;160000;160000;140000;150000;150000;150000;150000;150000;150000;150000;150000;150000;150000;150000;150000;150000;</T>
            <T>;150000;150000;150000;150000;150000;150000;150000;150000;140000;130000;140000;140000;150000;160000;160000;160000;150000;150000;150000;160000;</T>
            <T>;160000;160000;150000;140000;140000;130000;130000;130000;140000;110000;110000;110000;120000;110000;100000;120000;110000;100000;100000;110000;</T>
            <T>;120000;140000;120000;130000;140000;130000;150000;170000;200000;200000;200000;200000;200000;190000;190000;200000;200000;200000;200000;240000;</T>
            <T>;240000;230000;230000;220000;230000;210000;200000;210000;200000;210000;190000;190000;180000;200000;200000;200000;210000;210000;210000;200000;</T>
            <T>;190000;210000;210000;210000;200000;190000;190000;180000;190000;200000;200000;200000;180000;180000;190000;200000;200000;200000;200000;190000;</T>
            <T>;180000;180000;170000;190000;190000;180000;170000;170000;160000;160000;150000;170000;160000;160000;130000;130000;130000;140000;130000;130000;</T>
            <T>;140000;130000;130000;130000;130000;170000;170000;250000;340000;430000;550000;550000;570000;570000;630000;680000;960000;960000;1200000;1220000;</T>
            <T>;1280000;1410000;1480000;1640000;1980000;2150000;2120000;2320000;2320000;2530000;2690000;2880000;3050000;3080000;3010000;3230000;3290000;3250000;3160000;3160000;</T>
            <T>;3040000;2940000;3010000;3160000;3110000;3100000;3240000;3320000;3330000;3280000;3280000;3130000;3000000;2930000;2900000;2890000;2870000;2830000;2780000;2740000;</T>
            <T>;2640000;2640000;2540000;2420000;2320000;2220000;2120000;2040000;1960000;1890000;1800000;1750000;1750000;1680000;1650000;1630000;1600000;1580000;1580000;1590000;</T>
            <T>;1600000;1630000;1620000;1620000;1640000;1660000;1700000;1730000;1750000;1730000;1690000;1660000;1650000;1690000;1690000;1660000;1620000;1590000;1560000;1520000;</T>
            <T>;1480000;1440000;1410000;1370000;1320000;1320000;1290000;1270000;1240000;1180000;1150000;1120000;1070000;1030000;990000;970000;970000;950000;920000;870000;</T>
            <T>;840000;800000;760000;740000;710000;680000;630000;630000;630000;630000;630000;630000;630000;630000;630000;630000;630000;640000;630000;600000;</T>
            <T>;580000;580000;570000;550000;530000;540000;550000;540000;550000;550000;560000;570000;560000;550000;530000;510000;470000;470000;470000;470000;</T>
            <T>;450000;460000;440000;450000;470000;480000;490000;490000;500000;500000;510000;510000;490000;470000;460000;460000;450000;440000;420000;420000;</T>
            <T>;420000;420000;410000;410000;400000;400000;380000;370000;360000;360000;380000;420000;420000;410000;410000;420000;430000;400000;390000;380000;</T>
            <T>;360000;350000;320000;320000;320000;310000;300000;300000;290000;270000;260000;260000;260000;260000;240000;250000;260000;260000;260000;250000;</T>
            <T>;250000;230000;230000;220000;210000;190000;190000;220000;250000;280000;290000;290000;300000;330000;360000;380000;410000;400000;380000;380000;</T>
            <T>;360000;350000;350000;350000;340000;330000;310000;300000;310000;310000;310000;310000;300000;300000;290000;280000;280000;290000;310000;290000;</T>
            <T>;280000;270000;260000;260000;260000;250000;250000;250000;250000;250000;250000;230000;240000;260000;260000;250000;260000;250000;250000;240000;</T>
            <T>;230000;260000;260000;260000;240000;230000;240000;230000;220000;230000;250000;260000;260000;240000;230000;230000;230000;220000;220000;230000;</T>
            <T>;220000;220000;240000;270000;260000;260000;260000;250000;240000;230000;230000;220000;220000;190000;200000;190000;190000;200000;200000;210000;</T>
            <T>;210000;200000;200000;210000;200000;200000;210000;200000;190000;190000;200000;200000;200000;180000;190000;170000;180000;170000;170000;170000;</T>
            <T>;170000;170000;170000;190000;170000;170000;170000;160000;160000;150000;160000;170000;180000;150000;150000;160000;180000;190000;210000;220000;</T>
            <T>;210000;210000;230000;270000;280000;280000;270000;260000;260000;250000;260000;270000;280000;260000;250000;240000;240000;230000;210000;230000;</T>
            <T>;210000;200000;200000;220000;200000;200000;200000;210000;210000;200000;210000;200000;220000;220000;210000;210000;210000;200000;200000;200000;</T>
            <T>;200000;200000;190000;190000;190000;190000;190000;190000;190000;190000;210000;220000;240000;230000;220000;220000;210000;210000;210000;200000;</T>
            <T>;190000;180000;190000;200000;200000;190000;180000;180000;160000;160000;170000;</T>
          </X4>
        </X3>
      </X2>
    </X1>
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="2" A3="S" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="2" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="2" A3="E" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'18/06/2018 8:58:46'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;180000,000&quot;;EMG_MAXLEUVEN=&quot;0621,000&quot;;EMG_MAXV=&quot;2780000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0000,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0002,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806180859,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="180000" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="7635.51886332698" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="621" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 2538957" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="180517.695684524" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'18/06/2018 8:58:46'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;180517,696&quot;;EMG_MAXGENT=&quot;0622,000&quot;;EMG_MAXV=&quot;2538957,000&quot;;EMG_AMPL=&quot;2358439,304&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;0038,000&quot;;EMG_L3XRL=&quot;0037,000&quot;;EMG_L3XDIF=&quot;0026,000&quot;;DATEMARKER#G=&quot;1806180859,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="622" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="541553.087053572" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="588" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="587" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="576" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="2358439.30431548" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="38" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="37" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="26" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=7635.51886332698" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=180517.695684524" A3="U" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1001" A3="E" />