<?xml version="1.0"?>
<!DOCTYPE XML[
<!ELEMENT XML (X0*,T*)>
<!ELEMENT X0 (X1*,T*)>
<!ELEMENT X1 (X2*,T*)>
<!ELEMENT X2 (X3*,T*)>
<!ELEMENT X3 (X4*,T*)>
<!ELEMENT X4 (X5*,T*)>
<!ELEMENT X5 (X6*,T*)>
<!ELEMENT X6 (X7*,T*)>
<!ELEMENT X7 (X8*,T*)>
<!ELEMENT X8 (X9*,T*)>
<!ELEMENT X9 (EMPTY)>
<!ELEMENT T (#PCDATA)>
<!ATTLIST X0 A0 CDATA #IMPLIED>
<!ATTLIST X0 A1 CDATA #IMPLIED>
<!ATTLIST X0 A2 CDATA #IMPLIED>
<!ATTLIST X0 A3 CDATA #IMPLIED>
<!ATTLIST X0 A4 CDATA #IMPLIED>
<!ATTLIST X0 A5 CDATA #IMPLIED>
<!ATTLIST X0 A6 CDATA #IMPLIED>
<!ATTLIST X0 A7 CDATA #IMPLIED>
<!ATTLIST X0 A8 CDATA #IMPLIED>
<!ATTLIST X0 A9 CDATA #IMPLIED>
<!ATTLIST X1 A0 CDATA #IMPLIED>
<!ATTLIST X1 A1 CDATA #IMPLIED>
<!ATTLIST X1 A2 CDATA #IMPLIED>
<!ATTLIST X1 A3 CDATA #IMPLIED>
<!ATTLIST X1 A4 CDATA #IMPLIED>
<!ATTLIST X1 A5 CDATA #IMPLIED>
<!ATTLIST X1 A6 CDATA #IMPLIED>
<!ATTLIST X1 A7 CDATA #IMPLIED>
<!ATTLIST X1 A8 CDATA #IMPLIED>
<!ATTLIST X1 A9 CDATA #IMPLIED>
<!ATTLIST X2 A0 CDATA #IMPLIED>
<!ATTLIST X2 A1 CDATA #IMPLIED>
<!ATTLIST X2 A2 CDATA #IMPLIED>
<!ATTLIST X2 A3 CDATA #IMPLIED>
<!ATTLIST X2 A4 CDATA #IMPLIED>
<!ATTLIST X2 A5 CDATA #IMPLIED>
<!ATTLIST X2 A6 CDATA #IMPLIED>
<!ATTLIST X2 A7 CDATA #IMPLIED>
<!ATTLIST X2 A8 CDATA #IMPLIED>
<!ATTLIST X2 A9 CDATA #IMPLIED>
<!ATTLIST X3 A0 CDATA #IMPLIED>
<!ATTLIST X3 A1 CDATA #IMPLIED>
<!ATTLIST X3 A2 CDATA #IMPLIED>
<!ATTLIST X3 A3 CDATA #IMPLIED>
<!ATTLIST X3 A4 CDATA #IMPLIED>
<!ATTLIST X3 A5 CDATA #IMPLIED>
<!ATTLIST X3 A6 CDATA #IMPLIED>
<!ATTLIST X3 A7 CDATA #IMPLIED>
<!ATTLIST X3 A8 CDATA #IMPLIED>
<!ATTLIST X3 A9 CDATA #IMPLIED>
<!ATTLIST X4 A0 CDATA #IMPLIED>
<!ATTLIST X4 A1 CDATA #IMPLIED>
<!ATTLIST X4 A2 CDATA #IMPLIED>
<!ATTLIST X4 A3 CDATA #IMPLIED>
<!ATTLIST X4 A4 CDATA #IMPLIED>
<!ATTLIST X4 A5 CDATA #IMPLIED>
<!ATTLIST X4 A6 CDATA #IMPLIED>
<!ATTLIST X4 A7 CDATA #IMPLIED>
<!ATTLIST X4 A8 CDATA #IMPLIED>
<!ATTLIST X4 A9 CDATA #IMPLIED>
<!ATTLIST X5 A0 CDATA #IMPLIED>
<!ATTLIST X5 A1 CDATA #IMPLIED>
<!ATTLIST X5 A2 CDATA #IMPLIED>
<!ATTLIST X5 A3 CDATA #IMPLIED>
<!ATTLIST X5 A4 CDATA #IMPLIED>
<!ATTLIST X5 A5 CDATA #IMPLIED>
<!ATTLIST X5 A6 CDATA #IMPLIED>
<!ATTLIST X5 A7 CDATA #IMPLIED>
<!ATTLIST X5 A8 CDATA #IMPLIED>
<!ATTLIST X5 A9 CDATA #IMPLIED>
<!ATTLIST X6 A0 CDATA #IMPLIED>
<!ATTLIST X6 A1 CDATA #IMPLIED>
<!ATTLIST X6 A2 CDATA #IMPLIED>
<!ATTLIST X6 A3 CDATA #IMPLIED>
<!ATTLIST X6 A4 CDATA #IMPLIED>
<!ATTLIST X6 A5 CDATA #IMPLIED>
<!ATTLIST X6 A6 CDATA #IMPLIED>
<!ATTLIST X6 A7 CDATA #IMPLIED>
<!ATTLIST X6 A8 CDATA #IMPLIED>
<!ATTLIST X6 A9 CDATA #IMPLIED>
<!ATTLIST X7 A0 CDATA #IMPLIED>
<!ATTLIST X7 A1 CDATA #IMPLIED>
<!ATTLIST X7 A2 CDATA #IMPLIED>
<!ATTLIST X7 A3 CDATA #IMPLIED>
<!ATTLIST X7 A4 CDATA #IMPLIED>
<!ATTLIST X7 A5 CDATA #IMPLIED>
<!ATTLIST X7 A6 CDATA #IMPLIED>
<!ATTLIST X7 A7 CDATA #IMPLIED>
<!ATTLIST X7 A8 CDATA #IMPLIED>
<!ATTLIST X7 A9 CDATA #IMPLIED>
<!ATTLIST X8 A0 CDATA #IMPLIED>
<!ATTLIST X8 A1 CDATA #IMPLIED>
<!ATTLIST X8 A2 CDATA #IMPLIED>
<!ATTLIST X8 A3 CDATA #IMPLIED>
<!ATTLIST X8 A4 CDATA #IMPLIED>
<!ATTLIST X8 A5 CDATA #IMPLIED>
<!ATTLIST X8 A6 CDATA #IMPLIED>
<!ATTLIST X8 A7 CDATA #IMPLIED>
<!ATTLIST X8 A8 CDATA #IMPLIED>
<!ATTLIST X8 A9 CDATA #IMPLIED>
<!ATTLIST X9 A0 CDATA #IMPLIED>
<!ATTLIST X9 A1 CDATA #IMPLIED>
<!ATTLIST X9 A2 CDATA #IMPLIED>
<!ATTLIST X9 A3 CDATA #IMPLIED>
<!ATTLIST X9 A4 CDATA #IMPLIED>
<!ATTLIST X9 A5 CDATA #IMPLIED>
<!ATTLIST X9 A6 CDATA #IMPLIED>
<!ATTLIST X9 A7 CDATA #IMPLIED>
<!ATTLIST X9 A8 CDATA #IMPLIED>
<!ATTLIST X9 A9 CDATA #IMPLIED>
]>
<XML>
  <X0 A0="COMMENT">
    <T>P=PARAMETER;PS=PARAMETERS;T=TRIAL;TS=TRIALS;TPS=TRIALPARAMTERS;
	DP=DATAPOINT;DPS=DATAPOINTS;DPPS=DATAPOINTSPARAMETERS
	PARAMETER:
	N=NAME;P=protection code : U=USER;E=EXPERIMENT
	T=TYPE
	D = extra tag data dictionary</T>
  </X0>
  <X0 A0="PS">
    <X1 A0="P" A1="UPDCREATED" A2="UPD040907" A3="E" />
    <X1 A0="P" A1="IMPORTFILEDATA" A2="11/01/2018 9:55:14" A3="S" />
    <X1 A0="P" A1="FILENAME" A2="11/01/2018 9:55:14" A3="S" />
    <X1 A0="P" A1="EXP:DATATYPE" A2="LEUVEN2007:data" A3="E" />
    <X1 A0="P" A1="VOLFLOW" A2="T" A3="E" />
    <X1 A0="P" A1="FROMAFFECT" A2="T" A3="E" />
    <X1 A0="P" A1="PNEUMOSCRIPT" A2="" A3="E" />
    <X1 A0="P" A1="CH7:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="CH8:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="MAXSAMPLES" A2="151520" A3="E" />
    <X1 A0="P" A1="PROFILE" A2="LEUVEN2007" A3="E" />
    <X1 A0="P" A1="PHUID" A2="5013" A3="U" />
    <X1 A0="P" A1="CH2DISPLAY" A2="DisplayON=T;MyName=CH8;DType=12;Upper=39410000;Lower=80000;Persistent=T;;DType=12;MyName=W1;Upper=34396240;Persistent=T;Lower=-165637;;MyName=W2;DType=12;Upper=0;Persistent=T;Lower=0;;DType=12;MyName=W3;Upper=39410000;Persistent=T;Lower=80000;;DType=12;MyName=CH7;Upper=3941;Lower=8;Persistent=T;;DType=1;MyName=X;Upper=1011;Lower=0;Persistent=T" A3="U" />
    <X1 A0="P" A1="SHOWSTRIPEMODE" A2="ALL" A3="U" />
    <X1 A0="P" A1="CURRENTCH" A2="CH8" A3="U" />
    <X1 A0="P" A1="DATEMARKER" A2="1801111001" A3="U" />
    <X1 A0="P" A1="HIDEMARKERS" A2="" A3="U" />
    <X1 A0="P" A1="OUT_CH8BIS" A2="OUTPUTEXT=&quot;.EMGBIS.CSV&quot;;DISPLAYWITH=&quot;CH7&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_MEAN=&quot;MEAN&quot;;EMG_MAXGENT=&quot;MAXGENT&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_AMPL=&quot;AMPLITUDO&quot;;EMG_LMAX=&quot;LATENCYMAX&quot;;EMG_L3XLR=&quot;LATNCY3XLR&quot;;EMG_L3XRL=&quot;LATNCY3XRL&quot;;EMG_L3XDIF=&quot;LATNCY3XDIF&quot;;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SPECIALGROUP" A2="" A3="U" />
    <X1 A0="P" A1="EMG:SENS100" A2="100" A3="U" />
    <X1 A0="P" A1="EMG:SENS1000" A2="1000" A3="U" />
    <X1 A0="P" A1="EMG:SENS5000" A2="5000" A3="U" />
    <X1 A0="P" A1="EMG:SENS10000" A2="10000" A3="U" />
    <X1 A0="P" A1="EMG:SENS50000" A2="50000" A3="U" />
    <X1 A0="P" A1="OUT_CH8" A2="OUTPUTEXT=&quot;.EMG.CSV&quot;;DISPLAYWITH=&quot;CH8&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_BL=&quot;BASELINE&quot;;EMG_MAXLEUVEN=&quot;MAXLEUVEN&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_REJECT=&quot;REJECT&quot;;EMG_NON_RESPONS=&quot;NON_RESPPONS&quot;;CH8:PAS:Stimulus#G=Stimulus;CH8:PAS:Total_Trial_Nr#G=Total_Trial_Nr;CH8:PAS:practice#G=practice;CH8:PAS:acq#G=acq;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SRCFILEINFO" A2="" A3="U" />
  </X0>
  <X0 A0="iLOG" />
  <X0 A0="TS">
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="1" A3="S" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="1" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="0" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
        <X3 A0="P" A1="CH7REPOTR" A2="" A3="U" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'11/01/2018 9:55:14'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;350000,000&quot;;EMG_MAXLEUVEN=&quot;0636,000&quot;;EMG_MAXV=&quot;530000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0000,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0001,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1801111001,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="350000" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="4104.22216870519" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="636" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 496311.2" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="346168.895833333" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'11/01/2018 9:55:14'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;346168,896&quot;;EMG_MAXGENT=&quot;0637,000&quot;;EMG_MAXV=&quot;496311,200&quot;;EMG_AMPL=&quot;150142,304&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;9999,000&quot;;EMG_L3XRL=&quot;9999,000&quot;;EMG_L3XDIF=&quot;0030,000&quot;;DATEMARKER#G=&quot;1801111001,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="637" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="1038506.6875" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="580" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="150142.304166667" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="30" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=4104.22216870519" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=346168.895833333" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1127" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="CORE=34" A2="S=OK;V=550;C=255;E=" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1126;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;37;41;42;42;43;44;45;43;42;42;44;48;51;51;51;52;50;53;56;66;</T>
            <T>;68;69;68;68;67;66;88;111;115;130;143;153;154;156;156;163;165;164;158;154;</T>
            <T>;152;170;176;171;168;168;170;167;160;156;153;156;180;201;201;204;204;208;202;209;</T>
            <T>;213;236;237;245;237;226;216;216;208;201;193;194;196;197;197;194;186;179;179;174;</T>
            <T>;172;168;162;158;151;145;141;137;133;133;130;127;123;120;115;110;106;106;105;103;</T>
            <T>;103;102;102;106;104;104;102;99;98;98;100;100;98;96;95;95;94;92;88;87;</T>
            <T>;85;85;85;82;79;76;71;72;75;77;79;76;76;76;77;77;76;77;78;79;</T>
            <T>;80;81;82;83;83;82;83;83;79;79;77;77;77;77;80;80;81;81;80;78;</T>
            <T>;75;73;71;68;66;64;64;62;60;60;56;54;52;50;50;49;50;50;50;48;</T>
            <T>;49;49;51;51;51;51;50;51;51;54;56;58;56;56;59;61;64;65;67;67;</T>
            <T>;65;64;62;62;59;57;56;55;53;52;52;52;49;48;45;44;43;42;40;39;</T>
            <T>;37;37;36;34;32;34;33;32;31;30;29;28;28;28;28;28;25;26;25;24;</T>
            <T>;25;25;26;26;26;25;25;25;24;24;24;24;23;23;23;24;24;24;22;21;</T>
            <T>;21;22;23;22;24;24;25;25;26;28;27;26;25;24;23;22;22;23;22;25;</T>
            <T>;23;22;22;22;21;22;22;22;20;20;20;21;20;21;20;20;20;21;21;26;</T>
            <T>;27;28;28;31;32;35;35;36;35;35;37;37;38;43;42;42;41;41;40;39;</T>
            <T>;39;40;41;41;37;37;37;36;35;34;35;35;33;32;31;33;32;32;31;30;</T>
            <T>;31;32;32;34;32;34;32;32;31;33;33;34;33;33;32;31;29;31;30;29;</T>
            <T>;28;29;29;29;29;29;29;30;27;27;27;27;27;26;25;25;24;25;23;25;</T>
            <T>;28;26;25;25;24;23;23;23;25;26;24;23;24;24;26;28;29;29;28;28;</T>
            <T>;28;31;30;30;29;28;27;26;26;30;31;30;27;27;28;29;31;32;32;32;</T>
            <T>;32;33;32;33;33;36;41;47;54;55;55;57;60;63;63;65;67;66;66;66;</T>
            <T>;66;66;67;66;64;65;63;62;61;59;56;53;53;52;50;48;47;44;44;45;</T>
            <T>;45;44;44;44;44;43;41;44;43;42;42;41;39;38;38;37;38;40;41;40;</T>
            <T>;41;40;39;41;41;41;38;37;36;37;36;36;36;36;37;36;36;35;33;33;</T>
            <T>;32;31;33;34;35;37;36;36;36;36;37;39;37;38;40;43;44;43;43;43;</T>
            <T>;42;42;38;37;38;38;39;39;39;39;39;39;40;40;39;37;36;35;33;35;</T>
            <T>;35;34;34;36;33;33;34;34;34;35;35;35;35;35;35;35;35;35;35;35;</T>
            <T>;35;35;35;35;35;35;35;35;35;35;35;35;35;35;35;35;35;35;35;35;</T>
            <T>;35;35;35;35;35;37;39;40;43;43;42;41;42;44;44;45;44;45;43;43;</T>
            <T>;42;40;43;45;44;44;43;41;41;39;39;37;35;34;33;32;32;33;31;30;</T>
            <T>;29;31;31;32;34;35;38;40;45;47;48;49;48;49;50;51;53;52;49;49;</T>
            <T>;47;47;47;46;45;42;42;39;43;43;44;43;41;41;40;40;40;40;39;37;</T>
            <T>;36;36;38;37;36;35;35;33;32;31;32;31;30;29;29;31;32;32;34;32;</T>
            <T>;32;30;30;29;29;29;30;32;32;32;34;33;33;33;33;32;31;31;30;30;</T>
            <T>;31;31;31;31;30;31;31;32;31;31;31;30;30;29;31;31;36;44;50;52;</T>
            <T>;53;53;52;51;52;53;52;51;50;53;54;56;56;56;61;64;85;102;101;98;</T>
            <T>;96;99;113;113;116;114;130;143;158;172;171;172;188;228;228;243;245;255;257;250;</T>
            <T>;239;231;223;218;216;216;217;213;207;201;192;188;183;175;166;160;160;154;148;143;</T>
            <T>;140;139;136;134;132;129;130;130;131;128;123;124;129;134;138;144;153;160;160;162;</T>
            <T>;166;170;174;175;174;173;170;168;167;167;167;166;164;161;157;156;155;152;148;142;</T>
            <T>;142;137;133;130;129;125;120;116;114;110;107;107;105;100;96;91;88;86;83;80;</T>
            <T>;77;73;73;70;68;65;65;63;61;62;61;59;59;59;58;57;56;53;55;55;</T>
            <T>;55;53;52;52;52;50;48;47;49;48;46;45;44;44;42;42;41;39;39;38;</T>
            <T>;37;36;35;34;35;35;35;33;33;32;34;36;38;37;38;37;36;36;36;37;</T>
            <T>;39;38;37;38;39;39;39;38;38;38;40;41;45;45;45;44;42;39;39;39;</T>
            <T>;39;37;37;35;33;33;32;32;35;36;36;34;33;32;33;33;32;33;32;32;</T>
            <T>;32;32;32;31;32;32;34;37;36;36;36;36;36;34;33;32;33;32;31;31;</T>
            <T>;32;33;34;34;34;36;39;38;37;35;36;36;36;35;35;34;34;33;34;34;</T>
            <T>;34;32;31;31;30;30;30;30;30;28;28;28;27;28;27;28;28;27;27;29;</T>
            <T>;31;31;30;30;29;27;27;27;29;28;27;26;27;27;27;27;28;27;27;27;</T>
            <T>;28;30;33;35;36;37;36;37;36;36;35;35;34;33;34;33;32;33;34;34;</T>
            <T>;34;33;33;34;35;35;35;34;32;32;32;32;31;31;31;30;29;29;29;29;</T>
            <T>;27;27;27;27;26;27;30;29;28;30;32;31;29;29;32;33;35;32;33;33;</T>
            <T>;33;34;35;34;34;32;32;30;31;30;29;29;28;27;28;28;28;30;30;28;</T>
            <T>;27;26;26;25;24;24;24;22;23;22;24;24;24;23;24;22;22;22;21;21;</T>
            <T>;21;19;19;19;20;19;19;</T>
          </X4>
        </X3>
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH8" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1127" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="#OK" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="CORE=34" A2="S=OK;V=550;C=255;E=" A3="E" />
            <X5 A0="M" A1="MIN" A2="A=340703.94;S=OK;V=559;C=8421376;PHUID=PH1135;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=354280.44;S=OK;V=572;C=16711935;PHUID=PH1131;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=351174.44;S=OK;V=578;C=8421376;PHUID=PH1136;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=458714.94;S=OK;V=599;C=16711935;PHUID=PH1132;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=312081.12;S=OK;V=617;C=8421376;PHUID=PH1137;E=0" A3="U" />
            <X5 A0="M" A1="MAXLEUVEN" A2="TCOLOR=65280;A=0;S=OK;V=636;C=65280;PHUID=PH1142;E=0" A3="U" />
            <X5 A0="M" A1="MAXGENT" A2="TCOLOR=16711935;A=0;S=OK;V=637;C=16711935;PHUID=PH1141;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="C=16711935;E=0;SHM=ON;V=637;PHUID=PH1133;S=HIDE;A=496311.16" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=295617.22;S=OK;V=680;C=8421376;PHUID=PH1138;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=330395.59;S=OK;V=693;C=16711935;PHUID=PH1134;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=289341.38;S=OK;V=706;C=8421376;PHUID=PH1139;E=0" A3="U" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1126;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;370000;410000;420000;420000;430000;440000;450000;430000;420000;420000;440000;480000;510000;510000;510000;520000;500000;530000;560000;660000;</T>
            <T>;680000;690000;680000;680000;670000;660000;880000;1110000;1150000;1300000;1430000;1530000;1540000;1560000;1560000;1630000;1650000;1640000;1580000;1540000;</T>
            <T>;1520000;1700000;1760000;1710000;1680000;1680000;1700000;1670000;1600000;1560000;1530000;1560000;1800000;2010000;2010000;2040000;2040000;2080000;2020000;2090000;</T>
            <T>;2130000;2360000;2370000;2450000;2370000;2260000;2160000;2160000;2080000;2010000;1930000;1940000;1960000;1970000;1970000;1940000;1860000;1790000;1790000;1740000;</T>
            <T>;1720000;1680000;1620000;1580000;1510000;1450000;1410000;1370000;1330000;1330000;1300000;1270000;1230000;1200000;1150000;1100000;1060000;1060000;1050000;1030000;</T>
            <T>;1030000;1020000;1020000;1060000;1040000;1040000;1020000;990000;980000;980000;1000000;1000000;980000;960000;950000;950000;940000;920000;880000;870000;</T>
            <T>;850000;850000;850000;820000;790000;760000;710000;720000;750000;770000;790000;760000;760000;760000;770000;770000;760000;770000;780000;790000;</T>
            <T>;800000;810000;820000;830000;830000;820000;830000;830000;790000;790000;770000;770000;770000;770000;800000;800000;810000;810000;800000;780000;</T>
            <T>;750000;730000;710000;680000;660000;640000;640000;620000;600000;600000;560000;540000;520000;500000;500000;490000;500000;500000;500000;480000;</T>
            <T>;490000;490000;510000;510000;510000;510000;500000;510000;510000;540000;560000;580000;560000;560000;590000;610000;640000;650000;670000;670000;</T>
            <T>;650000;640000;620000;620000;590000;570000;560000;550000;530000;520000;520000;520000;490000;480000;450000;440000;430000;420000;400000;390000;</T>
            <T>;370000;370000;360000;340000;320000;340000;330000;320000;310000;300000;290000;280000;280000;280000;280000;280000;250000;260000;250000;240000;</T>
            <T>;250000;250000;260000;260000;260000;250000;250000;250000;240000;240000;240000;240000;230000;230000;230000;240000;240000;240000;220000;210000;</T>
            <T>;210000;220000;230000;220000;240000;240000;250000;250000;260000;280000;270000;260000;250000;240000;230000;220000;220000;230000;220000;250000;</T>
            <T>;230000;220000;220000;220000;210000;220000;220000;220000;200000;200000;200000;210000;200000;210000;200000;200000;200000;210000;210000;260000;</T>
            <T>;270000;280000;280000;310000;320000;350000;350000;360000;350000;350000;370000;370000;380000;430000;420000;420000;410000;410000;400000;390000;</T>
            <T>;390000;400000;410000;410000;370000;370000;370000;360000;350000;340000;350000;350000;330000;320000;310000;330000;320000;320000;310000;300000;</T>
            <T>;310000;320000;320000;340000;320000;340000;320000;320000;310000;330000;330000;340000;330000;330000;320000;310000;290000;310000;300000;290000;</T>
            <T>;280000;290000;290000;290000;290000;290000;290000;300000;270000;270000;270000;270000;270000;260000;250000;250000;240000;250000;230000;250000;</T>
            <T>;280000;260000;250000;250000;240000;230000;230000;230000;250000;260000;240000;230000;240000;240000;260000;280000;290000;290000;280000;280000;</T>
            <T>;280000;310000;300000;300000;290000;280000;270000;260000;260000;300000;310000;300000;270000;270000;280000;290000;310000;320000;320000;320000;</T>
            <T>;320000;330000;320000;330000;330000;360000;410000;470000;540000;550000;550000;570000;600000;630000;630000;650000;670000;660000;660000;660000;</T>
            <T>;660000;660000;670000;660000;640000;650000;630000;620000;610000;590000;560000;530000;530000;520000;500000;480000;470000;440000;440000;450000;</T>
            <T>;450000;440000;440000;440000;440000;430000;410000;440000;430000;420000;420000;410000;390000;380000;380000;370000;380000;400000;410000;400000;</T>
            <T>;410000;400000;390000;410000;410000;410000;380000;370000;360000;370000;360000;360000;360000;360000;370000;360000;360000;350000;330000;330000;</T>
            <T>;320000;310000;330000;340000;350000;370000;360000;360000;360000;360000;370000;390000;370000;380000;400000;430000;440000;430000;430000;430000;</T>
            <T>;420000;420000;380000;370000;380000;380000;390000;390000;390000;390000;390000;390000;400000;400000;390000;370000;360000;350000;330000;350000;</T>
            <T>;350000;340000;340000;360000;330000;330000;340000;340000;340000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;</T>
            <T>;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;350000;</T>
            <T>;350000;350000;350000;350000;350000;370000;390000;400000;430000;430000;420000;410000;420000;440000;440000;450000;440000;450000;430000;430000;</T>
            <T>;420000;400000;430000;450000;440000;440000;430000;410000;410000;390000;390000;370000;350000;340000;330000;320000;320000;330000;310000;300000;</T>
            <T>;290000;310000;310000;320000;340000;350000;380000;400000;450000;470000;480000;490000;480000;490000;500000;510000;530000;520000;490000;490000;</T>
            <T>;470000;470000;470000;460000;450000;420000;420000;390000;430000;430000;440000;430000;410000;410000;400000;400000;400000;400000;390000;370000;</T>
            <T>;360000;360000;380000;370000;360000;350000;350000;330000;320000;310000;320000;310000;300000;290000;290000;310000;320000;320000;340000;320000;</T>
            <T>;320000;300000;300000;290000;290000;290000;300000;320000;320000;320000;340000;330000;330000;330000;330000;320000;310000;310000;300000;300000;</T>
            <T>;310000;310000;310000;310000;300000;310000;310000;320000;310000;310000;310000;300000;300000;290000;310000;310000;360000;440000;500000;520000;</T>
            <T>;530000;530000;520000;510000;520000;530000;520000;510000;500000;530000;540000;560000;560000;560000;610000;640000;850000;1020000;1010000;980000;</T>
            <T>;960000;990000;1130000;1130000;1160000;1140000;1300000;1430000;1580000;1720000;1710000;1720000;1880000;2280000;2280000;2430000;2450000;2550000;2570000;2500000;</T>
            <T>;2390000;2310000;2230000;2180000;2160000;2160000;2170000;2130000;2070000;2010000;1920000;1880000;1830000;1750000;1660000;1600000;1600000;1540000;1480000;1430000;</T>
            <T>;1400000;1390000;1360000;1340000;1320000;1290000;1300000;1300000;1310000;1280000;1230000;1240000;1290000;1340000;1380000;1440000;1530000;1600000;1600000;1620000;</T>
            <T>;1660000;1700000;1740000;1750000;1740000;1730000;1700000;1680000;1670000;1670000;1670000;1660000;1640000;1610000;1570000;1560000;1550000;1520000;1480000;1420000;</T>
            <T>;1420000;1370000;1330000;1300000;1290000;1250000;1200000;1160000;1140000;1100000;1070000;1070000;1050000;1000000;960000;910000;880000;860000;830000;800000;</T>
            <T>;770000;730000;730000;700000;680000;650000;650000;630000;610000;620000;610000;590000;590000;590000;580000;570000;560000;530000;550000;550000;</T>
            <T>;550000;530000;520000;520000;520000;500000;480000;470000;490000;480000;460000;450000;440000;440000;420000;420000;410000;390000;390000;380000;</T>
            <T>;370000;360000;350000;340000;350000;350000;350000;330000;330000;320000;340000;360000;380000;370000;380000;370000;360000;360000;360000;370000;</T>
            <T>;390000;380000;370000;380000;390000;390000;390000;380000;380000;380000;400000;410000;450000;450000;450000;440000;420000;390000;390000;390000;</T>
            <T>;390000;370000;370000;350000;330000;330000;320000;320000;350000;360000;360000;340000;330000;320000;330000;330000;320000;330000;320000;320000;</T>
            <T>;320000;320000;320000;310000;320000;320000;340000;370000;360000;360000;360000;360000;360000;340000;330000;320000;330000;320000;310000;310000;</T>
            <T>;320000;330000;340000;340000;340000;360000;390000;380000;370000;350000;360000;360000;360000;350000;350000;340000;340000;330000;340000;340000;</T>
            <T>;340000;320000;310000;310000;300000;300000;300000;300000;300000;280000;280000;280000;270000;280000;270000;280000;280000;270000;270000;290000;</T>
            <T>;310000;310000;300000;300000;290000;270000;270000;270000;290000;280000;270000;260000;270000;270000;270000;270000;280000;270000;270000;270000;</T>
            <T>;280000;300000;330000;350000;360000;370000;360000;370000;360000;360000;350000;350000;340000;330000;340000;330000;320000;330000;340000;340000;</T>
            <T>;340000;330000;330000;340000;350000;350000;350000;340000;320000;320000;320000;320000;310000;310000;310000;300000;290000;290000;290000;290000;</T>
            <T>;270000;270000;270000;270000;260000;270000;300000;290000;280000;300000;320000;310000;290000;290000;320000;330000;350000;320000;330000;330000;</T>
            <T>;330000;340000;350000;340000;340000;320000;320000;300000;310000;300000;290000;290000;280000;270000;280000;280000;280000;300000;300000;280000;</T>
            <T>;270000;260000;260000;250000;240000;240000;240000;220000;230000;220000;240000;240000;240000;230000;240000;220000;220000;220000;210000;210000;</T>
            <T>;210000;190000;190000;190000;200000;190000;190000;</T>
          </X4>
        </X3>
      </X2>
    </X1>
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="2" A3="S" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="7" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="7" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="2" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="5" A3="E" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'11/01/2018 9:55:14'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;483809,524&quot;;EMG_MAXLEUVEN=&quot;0618,000&quot;;EMG_MAXV=&quot;12240000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0007,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0002,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1801111001,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="483809.523809524" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="160791.699797113" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="618" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 1.133199E+07" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="503682.950892857" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'11/01/2018 9:55:14'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;503682,951&quot;;EMG_MAXGENT=&quot;0615,000&quot;;EMG_MAXV=&quot;11331990,000&quot;;EMG_AMPL=&quot;10828307,049&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;0038,000&quot;;EMG_L3XRL=&quot;0037,000&quot;;EMG_L3XDIF=&quot;0031,000&quot;;DATEMARKER#G=&quot;1801111001,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="615" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="1511048.85267857" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="588" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="587" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="581" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="10828307.0491071" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="38" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="37" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="31" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=160791.699797113" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=503682.950892857" A3="U" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1000" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />