<?xml version="1.0"?>
<!DOCTYPE XML[
<!ELEMENT XML (X0*,T*)>
<!ELEMENT X0 (X1*,T*)>
<!ELEMENT X1 (X2*,T*)>
<!ELEMENT X2 (X3*,T*)>
<!ELEMENT X3 (X4*,T*)>
<!ELEMENT X4 (X5*,T*)>
<!ELEMENT X5 (X6*,T*)>
<!ELEMENT X6 (X7*,T*)>
<!ELEMENT X7 (X8*,T*)>
<!ELEMENT X8 (X9*,T*)>
<!ELEMENT X9 (EMPTY)>
<!ELEMENT T (#PCDATA)>
<!ATTLIST X0 A0 CDATA #IMPLIED>
<!ATTLIST X0 A1 CDATA #IMPLIED>
<!ATTLIST X0 A2 CDATA #IMPLIED>
<!ATTLIST X0 A3 CDATA #IMPLIED>
<!ATTLIST X0 A4 CDATA #IMPLIED>
<!ATTLIST X0 A5 CDATA #IMPLIED>
<!ATTLIST X0 A6 CDATA #IMPLIED>
<!ATTLIST X0 A7 CDATA #IMPLIED>
<!ATTLIST X0 A8 CDATA #IMPLIED>
<!ATTLIST X0 A9 CDATA #IMPLIED>
<!ATTLIST X1 A0 CDATA #IMPLIED>
<!ATTLIST X1 A1 CDATA #IMPLIED>
<!ATTLIST X1 A2 CDATA #IMPLIED>
<!ATTLIST X1 A3 CDATA #IMPLIED>
<!ATTLIST X1 A4 CDATA #IMPLIED>
<!ATTLIST X1 A5 CDATA #IMPLIED>
<!ATTLIST X1 A6 CDATA #IMPLIED>
<!ATTLIST X1 A7 CDATA #IMPLIED>
<!ATTLIST X1 A8 CDATA #IMPLIED>
<!ATTLIST X1 A9 CDATA #IMPLIED>
<!ATTLIST X2 A0 CDATA #IMPLIED>
<!ATTLIST X2 A1 CDATA #IMPLIED>
<!ATTLIST X2 A2 CDATA #IMPLIED>
<!ATTLIST X2 A3 CDATA #IMPLIED>
<!ATTLIST X2 A4 CDATA #IMPLIED>
<!ATTLIST X2 A5 CDATA #IMPLIED>
<!ATTLIST X2 A6 CDATA #IMPLIED>
<!ATTLIST X2 A7 CDATA #IMPLIED>
<!ATTLIST X2 A8 CDATA #IMPLIED>
<!ATTLIST X2 A9 CDATA #IMPLIED>
<!ATTLIST X3 A0 CDATA #IMPLIED>
<!ATTLIST X3 A1 CDATA #IMPLIED>
<!ATTLIST X3 A2 CDATA #IMPLIED>
<!ATTLIST X3 A3 CDATA #IMPLIED>
<!ATTLIST X3 A4 CDATA #IMPLIED>
<!ATTLIST X3 A5 CDATA #IMPLIED>
<!ATTLIST X3 A6 CDATA #IMPLIED>
<!ATTLIST X3 A7 CDATA #IMPLIED>
<!ATTLIST X3 A8 CDATA #IMPLIED>
<!ATTLIST X3 A9 CDATA #IMPLIED>
<!ATTLIST X4 A0 CDATA #IMPLIED>
<!ATTLIST X4 A1 CDATA #IMPLIED>
<!ATTLIST X4 A2 CDATA #IMPLIED>
<!ATTLIST X4 A3 CDATA #IMPLIED>
<!ATTLIST X4 A4 CDATA #IMPLIED>
<!ATTLIST X4 A5 CDATA #IMPLIED>
<!ATTLIST X4 A6 CDATA #IMPLIED>
<!ATTLIST X4 A7 CDATA #IMPLIED>
<!ATTLIST X4 A8 CDATA #IMPLIED>
<!ATTLIST X4 A9 CDATA #IMPLIED>
<!ATTLIST X5 A0 CDATA #IMPLIED>
<!ATTLIST X5 A1 CDATA #IMPLIED>
<!ATTLIST X5 A2 CDATA #IMPLIED>
<!ATTLIST X5 A3 CDATA #IMPLIED>
<!ATTLIST X5 A4 CDATA #IMPLIED>
<!ATTLIST X5 A5 CDATA #IMPLIED>
<!ATTLIST X5 A6 CDATA #IMPLIED>
<!ATTLIST X5 A7 CDATA #IMPLIED>
<!ATTLIST X5 A8 CDATA #IMPLIED>
<!ATTLIST X5 A9 CDATA #IMPLIED>
<!ATTLIST X6 A0 CDATA #IMPLIED>
<!ATTLIST X6 A1 CDATA #IMPLIED>
<!ATTLIST X6 A2 CDATA #IMPLIED>
<!ATTLIST X6 A3 CDATA #IMPLIED>
<!ATTLIST X6 A4 CDATA #IMPLIED>
<!ATTLIST X6 A5 CDATA #IMPLIED>
<!ATTLIST X6 A6 CDATA #IMPLIED>
<!ATTLIST X6 A7 CDATA #IMPLIED>
<!ATTLIST X6 A8 CDATA #IMPLIED>
<!ATTLIST X6 A9 CDATA #IMPLIED>
<!ATTLIST X7 A0 CDATA #IMPLIED>
<!ATTLIST X7 A1 CDATA #IMPLIED>
<!ATTLIST X7 A2 CDATA #IMPLIED>
<!ATTLIST X7 A3 CDATA #IMPLIED>
<!ATTLIST X7 A4 CDATA #IMPLIED>
<!ATTLIST X7 A5 CDATA #IMPLIED>
<!ATTLIST X7 A6 CDATA #IMPLIED>
<!ATTLIST X7 A7 CDATA #IMPLIED>
<!ATTLIST X7 A8 CDATA #IMPLIED>
<!ATTLIST X7 A9 CDATA #IMPLIED>
<!ATTLIST X8 A0 CDATA #IMPLIED>
<!ATTLIST X8 A1 CDATA #IMPLIED>
<!ATTLIST X8 A2 CDATA #IMPLIED>
<!ATTLIST X8 A3 CDATA #IMPLIED>
<!ATTLIST X8 A4 CDATA #IMPLIED>
<!ATTLIST X8 A5 CDATA #IMPLIED>
<!ATTLIST X8 A6 CDATA #IMPLIED>
<!ATTLIST X8 A7 CDATA #IMPLIED>
<!ATTLIST X8 A8 CDATA #IMPLIED>
<!ATTLIST X8 A9 CDATA #IMPLIED>
<!ATTLIST X9 A0 CDATA #IMPLIED>
<!ATTLIST X9 A1 CDATA #IMPLIED>
<!ATTLIST X9 A2 CDATA #IMPLIED>
<!ATTLIST X9 A3 CDATA #IMPLIED>
<!ATTLIST X9 A4 CDATA #IMPLIED>
<!ATTLIST X9 A5 CDATA #IMPLIED>
<!ATTLIST X9 A6 CDATA #IMPLIED>
<!ATTLIST X9 A7 CDATA #IMPLIED>
<!ATTLIST X9 A8 CDATA #IMPLIED>
<!ATTLIST X9 A9 CDATA #IMPLIED>
]>
<XML>
  <X0 A0="COMMENT">
    <T>P=PARAMETER;PS=PARAMETERS;T=TRIAL;TS=TRIALS;TPS=TRIALPARAMTERS;
	DP=DATAPOINT;DPS=DATAPOINTS;DPPS=DATAPOINTSPARAMETERS
	PARAMETER:
	N=NAME;P=protection code : U=USER;E=EXPERIMENT
	T=TYPE
	D = extra tag data dictionary</T>
  </X0>
  <X0 A0="PS">
    <X1 A0="P" A1="UPDCREATED" A2="UPD040907" A3="E" />
    <X1 A0="P" A1="IMPORTFILEDATA" A2="14/06/2018 14:59:15" A3="S" />
    <X1 A0="P" A1="FILENAME" A2="14/06/2018 14:59:15" A3="S" />
    <X1 A0="P" A1="EXP:DATATYPE" A2="LEUVEN2007:data" A3="E" />
    <X1 A0="P" A1="VOLFLOW" A2="T" A3="E" />
    <X1 A0="P" A1="FROMAFFECT" A2="T" A3="E" />
    <X1 A0="P" A1="PNEUMOSCRIPT" A2="" A3="E" />
    <X1 A0="P" A1="CH7:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="CH8:PAS:" A2="Stimulus;Total_Trial_Nr;practice;acq" A3="E" />
    <X1 A0="P" A1="MAXSAMPLES" A2="154498" A3="E" />
    <X1 A0="P" A1="PROFILE" A2="LEUVEN2007" A3="E" />
    <X1 A0="P" A1="PHUID" A2="5208" A3="U" />
    <X1 A0="P" A1="CH2DISPLAY" A2="DisplayON=T;MyName=CH8;DType=12;Upper=7990000;Lower=70000;Persistent=T;;DType=12;MyName=W1;Upper=7038490;Persistent=T;Lower=0;;MyName=W2;DType=12;Upper=0;Persistent=T;Lower=0;;DType=12;MyName=W3;Upper=7990000;Persistent=T;Lower=70000;;DType=12;MyName=CH7;Upper=799;Lower=7;Persistent=T;;DType=1;MyName=X;Upper=1052;Lower=0;Persistent=T" A3="U" />
    <X1 A0="P" A1="SHOWSTRIPEMODE" A2="ALL" A3="U" />
    <X1 A0="P" A1="CURRENTCH" A2="CH8" A3="U" />
    <X1 A0="P" A1="DATEMARKER" A2="1806141459" A3="U" />
    <X1 A0="P" A1="HIDEMARKERS" A2="" A3="U" />
    <X1 A0="P" A1="OUT_CH8BIS" A2="OUTPUTEXT=&quot;.EMGBIS.CSV&quot;;DISPLAYWITH=&quot;CH7&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_MEAN=&quot;MEAN&quot;;EMG_MAXGENT=&quot;MAXGENT&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_AMPL=&quot;AMPLITUDO&quot;;EMG_LMAX=&quot;LATENCYMAX&quot;;EMG_L3XLR=&quot;LATNCY3XLR&quot;;EMG_L3XRL=&quot;LATNCY3XRL&quot;;EMG_L3XDIF=&quot;LATNCY3XDIF&quot;;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SPECIALGROUP" A2="" A3="U" />
    <X1 A0="P" A1="EMG:SENS100" A2="100" A3="U" />
    <X1 A0="P" A1="EMG:SENS1000" A2="1000" A3="U" />
    <X1 A0="P" A1="EMG:SENS5000" A2="5000" A3="U" />
    <X1 A0="P" A1="EMG:SENS10000" A2="10000" A3="U" />
    <X1 A0="P" A1="EMG:SENS50000" A2="50000" A3="U" />
    <X1 A0="P" A1="OUT_CH8" A2="OUTPUTEXT=&quot;.EMG.CSV&quot;;DISPLAYWITH=&quot;CH8&quot;;FILENAME#G=&quot;CLIENT&quot;;TRIAL:IDENT#G=&quot;TRIALN&quot;;EMG_KEY=&quot;KEY&quot;;EMG_BL=&quot;BASELINE&quot;;EMG_MAXLEUVEN=&quot;MAXLEUVEN&quot;;EMG_MAXV=&quot;MAXV&quot;;EMG_REJECT=&quot;REJECT&quot;;EMG_NON_RESPONS=&quot;NON_RESPPONS&quot;;CH8:PAS:Stimulus#G=Stimulus;CH8:PAS:Total_Trial_Nr#G=Total_Trial_Nr;CH8:PAS:practice#G=practice;CH8:PAS:acq#G=acq;DATEMARKER#G=&quot;DATE&quot;;#COMPACT=&quot;F&quot;" A3="U" />
    <X1 A0="P" A1="SRCFILEINFO" A2="" A3="U" />
  </X0>
  <X0 A0="iLOG" />
  <X0 A0="TS">
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="1" A3="S" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="1" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="PROCESSMODE" A2="" A3="U" />
        <X3 A0="P" A1="CH7REPOTR" A2="" A3="U" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'14/06/2018 14:59:15'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;840000,000&quot;;EMG_MAXLEUVEN=&quot;0641,000&quot;;EMG_MAXV=&quot;1100000,000&quot;;EMG_REJECT=&quot;1&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0010,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0001,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806141459,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="840000" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="30872.2873421602" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="641" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 1016213" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="835901.815476191" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'14/06/2018 14:59:15'&quot;;TRIAL:IDENT#G=&quot;0001,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;835901,815&quot;;EMG_MAXGENT=&quot;0643,000&quot;;EMG_MAXV=&quot;1016213,000&quot;;EMG_AMPL=&quot;180311,185&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;9999,000&quot;;EMG_L3XRL=&quot;9999,000&quot;;EMG_L3XDIF=&quot;0028,000&quot;;DATEMARKER#G=&quot;1806141459,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="643" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="2507705.44642857" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="578" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="180311.184523809" A3="U" />
        <X3 A0="P" A1="EMG_LMAX" A2="-550" A3="U" />
        <X3 A0="P" A1="EMG_L3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_L3XDIF" A2="28" A3="U" />
        <X3 A0="P" A1="EMG_STDEV_MERGE" A2=";ACT:PROBE=30872.2873421602" A3="U" />
        <X3 A0="P" A1="EMG_MEAN_MERGE" A2=";ACT:PROBE=835901.815476191" A3="U" />
        <X3 A0="P" A1="EMG_REJECT" A2="T" A3="U" />
      </X2>
      <X2 A0="DPS">
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH7" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1145" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=56" A2="S=OK;V=548;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1144;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;26;24;24;24;23;23;23;22;23;24;23;23;22;22;23;24;23;23;22;23;</T>
            <T>;23;23;23;23;23;22;22;21;20;21;21;20;19;20;20;20;19;21;21;22;</T>
            <T>;21;19;18;18;19;19;18;20;21;22;22;23;24;25;26;27;27;27;26;25;</T>
            <T>;26;27;24;24;25;25;25;25;24;24;22;21;22;23;24;23;21;21;21;21;</T>
            <T>;22;22;22;22;20;20;19;18;19;19;20;21;24;25;27;29;30;31;31;30;</T>
            <T>;30;30;30;32;38;44;51;57;62;66;71;71;75;78;81;87;90;91;91;91;</T>
            <T>;92;94;94;99;105;107;106;104;100;98;97;95;95;95;93;90;87;85;85;87;</T>
            <T>;86;85;85;83;83;84;85;88;92;96;98;100;103;105;107;107;111;115;117;119;</T>
            <T>;118;120;121;117;113;110;110;110;112;114;116;118;118;118;120;119;119;119;120;118;</T>
            <T>;117;115;112;111;109;107;105;103;103;103;102;102;101;97;92;88;85;82;79;79;</T>
            <T>;77;75;73;73;72;75;75;72;73;76;76;76;76;76;74;72;69;68;68;67;</T>
            <T>;64;64;64;65;65;65;63;62;60;58;56;55;55;54;52;52;52;50;49;48;</T>
            <T>;47;46;45;45;45;47;49;52;52;51;50;49;47;46;46;44;44;43;45;49;</T>
            <T>;48;46;44;44;42;42;41;39;39;38;37;37;37;38;38;37;37;35;34;34;</T>
            <T>;34;32;31;30;28;28;29;29;30;29;30;31;31;31;31;30;30;28;28;27;</T>
            <T>;26;26;28;30;27;26;26;26;26;26;25;25;25;25;24;25;25;24;24;25;</T>
            <T>;25;24;25;26;28;30;29;29;29;28;27;27;28;28;27;28;27;27;27;26;</T>
            <T>;26;30;30;34;34;35;38;40;38;38;42;44;46;46;48;50;49;47;45;45;</T>
            <T>;45;47;49;50;50;54;55;54;57;59;59;58;56;57;57;57;56;56;54;52;</T>
            <T>;51;51;49;48;47;47;47;45;43;43;43;48;53;53;52;53;55;55;58;59;</T>
            <T>;57;55;53;54;52;49;48;46;46;44;44;43;42;42;40;38;45;55;57;57;</T>
            <T>;58;65;67;68;70;71;68;66;64;64;64;63;60;58;58;58;56;55;56;55;</T>
            <T>;54;54;53;56;58;56;54;53;53;52;51;49;49;47;45;48;53;54;56;55;</T>
            <T>;55;59;60;60;62;64;63;63;60;59;59;58;56;54;54;55;61;68;69;68;</T>
            <T>;71;76;81;81;80;80;81;83;82;79;79;81;83;83;80;80;80;80;79;78;</T>
            <T>;77;76;74;79;87;94;100;100;104;104;100;96;92;92;93;90;88;85;85;81;</T>
            <T>;79;79;84;90;92;93;96;96;100;100;108;117;120;117;118;122;122;116;112;108;</T>
            <T>;108;105;101;97;92;90;85;84;84;84;84;84;84;84;84;84;84;84;84;84;</T>
            <T>;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;</T>
            <T>;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;84;</T>
            <T>;84;84;84;84;84;82;81;79;77;75;73;69;69;72;75;80;86;91;92;92;</T>
            <T>;90;88;83;79;76;76;77;75;77;83;88;90;92;91;87;84;83;90;99;105;</T>
            <T>;109;110;107;102;99;101;99;99;97;94;95;95;93;92;92;90;87;84;81;82;</T>
            <T>;87;86;83;82;84;85;87;88;90;92;91;87;84;81;80;77;75;74;71;71;</T>
            <T>;73;73;70;70;73;79;80;79;84;90;92;92;91;89;88;90;87;87;92;98;</T>
            <T>;100;96;94;92;88;86;83;81;81;78;77;79;78;76;78;81;82;80;78;78;</T>
            <T>;79;79;78;80;85;86;85;84;84;81;81;77;75;74;71;72;79;80;77;74;</T>
            <T>;75;75;74;72;69;70;71;70;70;71;70;70;70;69;67;65;65;63;64;65;</T>
            <T>;65;64;61;61;58;56;59;75;91;92;96;111;118;119;119;129;143;152;155;188;</T>
            <T>;210;213;234;247;272;272;290;286;312;345;357;355;343;336;323;315;315;316;307;294;</T>
            <T>;280;268;257;246;238;234;228;228;221;213;206;197;189;180;170;163;157;153;153;150;</T>
            <T>;147;143;142;141;143;145;146;148;150;150;151;152;153;154;153;151;151;153;154;154;</T>
            <T>;154;154;153;149;147;146;145;145;143;137;132;132;129;127;123;125;129;126;122;121;</T>
            <T>;119;117;117;115;112;111;114;109;108;106;107;108;108;108;105;102;103;100;99;95;</T>
            <T>;92;92;88;91;91;95;95;93;94;99;107;110;108;105;100;100;96;101;102;105;</T>
            <T>;117;118;120;124;123;126;126;123;123;126;127;123;125;126;122;121;117;117;115;122;</T>
            <T>;128;129;135;136;141;156;164;161;161;157;160;160;153;149;151;154;157;156;152;152;</T>
            <T>;148;145;141;138;137;130;133;145;149;145;145;147;149;151;151;150;158;166;162;167;</T>
            <T>;176;176;179;178;172;165;159;152;148;142;140;137;137;132;128;121;116;111;113;116;</T>
            <T>;113;109;108;108;104;104;105;101;99;95;92;92;93;93;93;89;87;84;80;80;</T>
            <T>;81;79;76;74;70;70;69;67;65;64;62;59;56;55;54;55;55;55;53;51;</T>
            <T>;50;48;47;48;49;48;48;48;47;46;45;44;44;42;42;43;42;42;42;43;</T>
            <T>;42;42;42;41;41;42;44;45;45;45;44;45;50;57;61;61;59;60;61;62;</T>
            <T>;62;60;59;57;57;56;61;69;76;78;75;75;74;78;85;86;85;86;88;88;</T>
            <T>;99;112;112;119;116;117;128;136;138;132;127;122;118;118;118;119;119;116;114;115;</T>
            <T>;120;125;129;137;137;142;138;137;141;151;163;162;157;157;154;154;150;148;145;142;</T>
            <T>;147;161;159;165;177;184;184;187;181;173;167;161;159;158;151;144;138;138;134;129;</T>
            <T>;126;124;131;136;132;</T>
          </X4>
        </X3>
        <X3 A0="DP">
          <X4 A0="PS">
            <X5 A0="P" A1="NAME" A2="CH8" A3="E" />
            <X5 A0="P" A1="SAMPLES" A2="1145" A3="E" />
            <X5 A0="P" A1="DSAMPLETIME" A2="1" A3="E" />
            <X5 A0="P" A1="TYPE" A2="E" A3="E" />
            <X5 A0="P" A1="EXITSTATUS" A2="#OK" A3="E" />
            <X5 A0="P" A1="DONOTPROCESS" A2="OFF" A3="E" />
            <X5 A0="P" A1="MMBYHAND" A2="OFF" A3="E" />
            <X5 A0="P" A1="DECIMALS" A2="2" A3="E" />
            <X5 A0="P" A1="INVERTED" A2="OFF" A3="E" />
            <X5 A0="M" A1="BOT" A2="S=OK;V=0;C=16711680;E=" A3="E" />
            <X5 A0="M" A1="ACT:SENSITIVITY" A2="S=OK;V=0;C=255;E=10000" A3="E" />
            <X5 A0="M" A1="CORE=56" A2="S=OK;V=548;C=255;E=" A3="E" />
            <X5 A0="M" A1="ACT:PROBE" A2="S=OK;V=550;C=0;E=1" A3="E" />
            <X5 A0="M" A1="MAX" A2="A=873587.12;S=OK;V=565;C=16711935;PHUID=PH1191;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=810900.5;S=OK;V=578;C=8421376;PHUID=PH1198;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=869049;S=OK;V=590;C=16711935;PHUID=PH1192;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=785267.12;S=OK;V=605;C=8421376;PHUID=PH1199;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=815610.38;S=OK;V=616;C=16711935;PHUID=PH1193;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=802668.44;S=OK;V=624;C=8421376;PHUID=PH1200;E=0" A3="U" />
            <X5 A0="M" A1="MAXLEUVEN" A2="TCOLOR=65280;A=0;S=OK;V=641;C=65280;PHUID=PH1207;E=0" A3="U" />
            <X5 A0="M" A1="MAXGENT" A2="TCOLOR=16711935;A=0;S=OK;V=643;C=16711935;PHUID=PH1206;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="C=16711935;E=0;SHM=ON;V=643;PHUID=PH1194;S=HIDE;A=1016212.75" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=851260;S=OK;V=662;C=8421376;PHUID=PH1201;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=853132.19;S=OK;V=666;C=16711935;PHUID=PH1195;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=743316.44;S=OK;V=682;C=8421376;PHUID=PH1202;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=948361.5;S=OK;V=698;C=16711935;PHUID=PH1196;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=760666.69;S=OK;V=715;C=8421376;PHUID=PH1203;E=0" A3="U" />
            <X5 A0="M" A1="MAX" A2="A=834184.31;S=OK;V=727;C=16711935;PHUID=PH1197;E=0" A3="U" />
            <X5 A0="M" A1="MIN" A2="A=698567.12;S=OK;V=744;C=8421376;PHUID=PH1204;E=0" A3="U" />
            <X5 A0="M" A1="EOT" A2="S=OK;V=1144;C=16711680;E=" A3="E" />
          </X4>
          <X4 A0="CS">
            <T>;260000;240000;240000;240000;230000;230000;230000;220000;230000;240000;230000;230000;220000;220000;230000;240000;230000;230000;220000;230000;</T>
            <T>;230000;230000;230000;230000;230000;220000;220000;210000;200000;210000;210000;200000;190000;200000;200000;200000;190000;210000;210000;220000;</T>
            <T>;210000;190000;180000;180000;190000;190000;180000;200000;210000;220000;220000;230000;240000;250000;260000;270000;270000;270000;260000;250000;</T>
            <T>;260000;270000;240000;240000;250000;250000;250000;250000;240000;240000;220000;210000;220000;230000;240000;230000;210000;210000;210000;210000;</T>
            <T>;220000;220000;220000;220000;200000;200000;190000;180000;190000;190000;200000;210000;240000;250000;270000;290000;300000;310000;310000;300000;</T>
            <T>;300000;300000;300000;320000;380000;440000;510000;570000;620000;660000;710000;710000;750000;780000;810000;870000;900000;910000;910000;910000;</T>
            <T>;920000;940000;940000;990000;1050000;1070000;1060000;1040000;1000000;980000;970000;950000;950000;950000;930000;900000;870000;850000;850000;870000;</T>
            <T>;860000;850000;850000;830000;830000;840000;850000;880000;920000;960000;980000;1000000;1030000;1050000;1070000;1070000;1110000;1150000;1170000;1190000;</T>
            <T>;1180000;1200000;1210000;1170000;1130000;1100000;1100000;1100000;1120000;1140000;1160000;1180000;1180000;1180000;1200000;1190000;1190000;1190000;1200000;1180000;</T>
            <T>;1170000;1150000;1120000;1110000;1090000;1070000;1050000;1030000;1030000;1030000;1020000;1020000;1010000;970000;920000;880000;850000;820000;790000;790000;</T>
            <T>;770000;750000;730000;730000;720000;750000;750000;720000;730000;760000;760000;760000;760000;760000;740000;720000;690000;680000;680000;670000;</T>
            <T>;640000;640000;640000;650000;650000;650000;630000;620000;600000;580000;560000;550000;550000;540000;520000;520000;520000;500000;490000;480000;</T>
            <T>;470000;460000;450000;450000;450000;470000;490000;520000;520000;510000;500000;490000;470000;460000;460000;440000;440000;430000;450000;490000;</T>
            <T>;480000;460000;440000;440000;420000;420000;410000;390000;390000;380000;370000;370000;370000;380000;380000;370000;370000;350000;340000;340000;</T>
            <T>;340000;320000;310000;300000;280000;280000;290000;290000;300000;290000;300000;310000;310000;310000;310000;300000;300000;280000;280000;270000;</T>
            <T>;260000;260000;280000;300000;270000;260000;260000;260000;260000;260000;250000;250000;250000;250000;240000;250000;250000;240000;240000;250000;</T>
            <T>;250000;240000;250000;260000;280000;300000;290000;290000;290000;280000;270000;270000;280000;280000;270000;280000;270000;270000;270000;260000;</T>
            <T>;260000;300000;300000;340000;340000;350000;380000;400000;380000;380000;420000;440000;460000;460000;480000;500000;490000;470000;450000;450000;</T>
            <T>;450000;470000;490000;500000;500000;540000;550000;540000;570000;590000;590000;580000;560000;570000;570000;570000;560000;560000;540000;520000;</T>
            <T>;510000;510000;490000;480000;470000;470000;470000;450000;430000;430000;430000;480000;530000;530000;520000;530000;550000;550000;580000;590000;</T>
            <T>;570000;550000;530000;540000;520000;490000;480000;460000;460000;440000;440000;430000;420000;420000;400000;380000;450000;550000;570000;570000;</T>
            <T>;580000;650000;670000;680000;700000;710000;680000;660000;640000;640000;640000;630000;600000;580000;580000;580000;560000;550000;560000;550000;</T>
            <T>;540000;540000;530000;560000;580000;560000;540000;530000;530000;520000;510000;490000;490000;470000;450000;480000;530000;540000;560000;550000;</T>
            <T>;550000;590000;600000;600000;620000;640000;630000;630000;600000;590000;590000;580000;560000;540000;540000;550000;610000;680000;690000;680000;</T>
            <T>;710000;760000;810000;810000;800000;800000;810000;830000;820000;790000;790000;810000;830000;830000;800000;800000;800000;800000;790000;780000;</T>
            <T>;770000;760000;740000;790000;870000;940000;1000000;1000000;1040000;1040000;1000000;960000;920000;920000;930000;900000;880000;850000;850000;810000;</T>
            <T>;790000;790000;840000;900000;920000;930000;960000;960000;1000000;1000000;1080000;1170000;1200000;1170000;1180000;1220000;1220000;1160000;1120000;1080000;</T>
            <T>;1080000;1050000;1010000;970000;920000;900000;850000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;</T>
            <T>;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;</T>
            <T>;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;840000;</T>
            <T>;840000;840000;840000;840000;840000;820000;810000;790000;770000;750000;730000;690000;690000;720000;750000;800000;860000;910000;920000;920000;</T>
            <T>;900000;880000;830000;790000;760000;760000;770000;750000;770000;830000;880000;900000;920000;910000;870000;840000;830000;900000;990000;1050000;</T>
            <T>;1090000;1100000;1070000;1020000;990000;1010000;990000;990000;970000;940000;950000;950000;930000;920000;920000;900000;870000;840000;810000;820000;</T>
            <T>;870000;860000;830000;820000;840000;850000;870000;880000;900000;920000;910000;870000;840000;810000;800000;770000;750000;740000;710000;710000;</T>
            <T>;730000;730000;700000;700000;730000;790000;800000;790000;840000;900000;920000;920000;910000;890000;880000;900000;870000;870000;920000;980000;</T>
            <T>;1000000;960000;940000;920000;880000;860000;830000;810000;810000;780000;770000;790000;780000;760000;780000;810000;820000;800000;780000;780000;</T>
            <T>;790000;790000;780000;800000;850000;860000;850000;840000;840000;810000;810000;770000;750000;740000;710000;720000;790000;800000;770000;740000;</T>
            <T>;750000;750000;740000;720000;690000;700000;710000;700000;700000;710000;700000;700000;700000;690000;670000;650000;650000;630000;640000;650000;</T>
            <T>;650000;640000;610000;610000;580000;560000;590000;750000;910000;920000;960000;1110000;1180000;1190000;1190000;1290000;1430000;1520000;1550000;1880000;</T>
            <T>;2100000;2130000;2340000;2470000;2720000;2720000;2900000;2860000;3120000;3450000;3570000;3550000;3430000;3360000;3230000;3150000;3150000;3160000;3070000;2940000;</T>
            <T>;2800000;2680000;2570000;2460000;2380000;2340000;2280000;2280000;2210000;2130000;2060000;1970000;1890000;1800000;1700000;1630000;1570000;1530000;1530000;1500000;</T>
            <T>;1470000;1430000;1420000;1410000;1430000;1450000;1460000;1480000;1500000;1500000;1510000;1520000;1530000;1540000;1530000;1510000;1510000;1530000;1540000;1540000;</T>
            <T>;1540000;1540000;1530000;1490000;1470000;1460000;1450000;1450000;1430000;1370000;1320000;1320000;1290000;1270000;1230000;1250000;1290000;1260000;1220000;1210000;</T>
            <T>;1190000;1170000;1170000;1150000;1120000;1110000;1140000;1090000;1080000;1060000;1070000;1080000;1080000;1080000;1050000;1020000;1030000;1000000;990000;950000;</T>
            <T>;920000;920000;880000;910000;910000;950000;950000;930000;940000;990000;1070000;1100000;1080000;1050000;1000000;1000000;960000;1010000;1020000;1050000;</T>
            <T>;1170000;1180000;1200000;1240000;1230000;1260000;1260000;1230000;1230000;1260000;1270000;1230000;1250000;1260000;1220000;1210000;1170000;1170000;1150000;1220000;</T>
            <T>;1280000;1290000;1350000;1360000;1410000;1560000;1640000;1610000;1610000;1570000;1600000;1600000;1530000;1490000;1510000;1540000;1570000;1560000;1520000;1520000;</T>
            <T>;1480000;1450000;1410000;1380000;1370000;1300000;1330000;1450000;1490000;1450000;1450000;1470000;1490000;1510000;1510000;1500000;1580000;1660000;1620000;1670000;</T>
            <T>;1760000;1760000;1790000;1780000;1720000;1650000;1590000;1520000;1480000;1420000;1400000;1370000;1370000;1320000;1280000;1210000;1160000;1110000;1130000;1160000;</T>
            <T>;1130000;1090000;1080000;1080000;1040000;1040000;1050000;1010000;990000;950000;920000;920000;930000;930000;930000;890000;870000;840000;800000;800000;</T>
            <T>;810000;790000;760000;740000;700000;700000;690000;670000;650000;640000;620000;590000;560000;550000;540000;550000;550000;550000;530000;510000;</T>
            <T>;500000;480000;470000;480000;490000;480000;480000;480000;470000;460000;450000;440000;440000;420000;420000;430000;420000;420000;420000;430000;</T>
            <T>;420000;420000;420000;410000;410000;420000;440000;450000;450000;450000;440000;450000;500000;570000;610000;610000;590000;600000;610000;620000;</T>
            <T>;620000;600000;590000;570000;570000;560000;610000;690000;760000;780000;750000;750000;740000;780000;850000;860000;850000;860000;880000;880000;</T>
            <T>;990000;1120000;1120000;1190000;1160000;1170000;1280000;1360000;1380000;1320000;1270000;1220000;1180000;1180000;1180000;1190000;1190000;1160000;1140000;1150000;</T>
            <T>;1200000;1250000;1290000;1370000;1370000;1420000;1380000;1370000;1410000;1510000;1630000;1620000;1570000;1570000;1540000;1540000;1500000;1480000;1450000;1420000;</T>
            <T>;1470000;1610000;1590000;1650000;1770000;1840000;1840000;1870000;1810000;1730000;1670000;1610000;1590000;1580000;1510000;1440000;1380000;1380000;1340000;1290000;</T>
            <T>;1260000;1240000;1310000;1360000;1320000;</T>
          </X4>
        </X3>
      </X2>
    </X1>
    <X1 A0="T">
      <X2 A0="PS">
        <X3 A0="P" A1="TRIALNUMBER" A2="2" A3="S" />
        <X3 A0="P" A1="CH7:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH8:PAS:STIMULUS" A2="10" A3="E" />
        <X3 A0="P" A1="CH7:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH8:PAS:TOTAL_TRIAL_NR" A2="2" A3="E" />
        <X3 A0="P" A1="CH7:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH8:PAS:PRACTICE" A2="1" A3="E" />
        <X3 A0="P" A1="CH7:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="CH8:PAS:ACQ" A2="0" A3="E" />
        <X3 A0="P" A1="TRIAL:IDENT" A2="2" A3="E" />
        <X3 A0="P" A1="TRIAL:STARTTIME" A2="1" A3="E" />
        <X3 A0="P" A1="OUT_CH8" A2="{FILENAME#G=&quot;'14/06/2018 14:59:15'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_BL=&quot;276190,476&quot;;EMG_MAXLEUVEN=&quot;0653,000&quot;;EMG_MAXV=&quot;1080000,000&quot;;EMG_REJECT=&quot;0&quot;;EMG_NON_RESPONS=&quot;0&quot;;CH8:PAS:Stimulus#G=&quot;0010,000&quot;;CH8:PAS:Total_Trial_Nr#G=&quot;0002,000&quot;;CH8:PAS:practice#G=&quot;0001,000&quot;;CH8:PAS:acq#G=&quot;0000,000&quot;;DATEMARKER#G=&quot;1806141459,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_BL" A2="276190.476190476" A3="U" />
        <X3 A0="P" A1="EMG_STDEV" A2="17105.237080089" A3="U" />
        <X3 A0="P" A1="EMG_MAXLEUVEN" A2="653" A3="U" />
        <X3 A0="P" A1="EMG_MAXV" A2=" 967288.1" A3="U" />
        <X3 A0="P" A1="EMG_KEY" A2="ACT:PROBE" A3="U" />
        <X3 A0="P" A1="EMG_MEAN" A2="274410.327380952" A3="U" />
        <X3 A0="P" A1="OUT_CH8BIS" A2="{FILENAME#G=&quot;'14/06/2018 14:59:15'&quot;;TRIAL:IDENT#G=&quot;0002,000&quot;;EMG_KEY=&quot;'ACT:PROB'&quot;;EMG_MEAN=&quot;274410,327&quot;;EMG_MAXGENT=&quot;0657,000&quot;;EMG_MAXV=&quot;967288,100&quot;;EMG_AMPL=&quot;692877,773&quot;;EMG_LMAX=&quot;-0550,000&quot;;EMG_L3XLR=&quot;9999,000&quot;;EMG_L3XRL=&quot;9999,000&quot;;EMG_L3XDIF=&quot;9999,000&quot;;DATEMARKER#G=&quot;1806141459,000&quot;;#COMPACT=&quot;F&quot;}" A3="U" />
        <X3 A0="P" A1="EMG_MAXGENT" A2="657" A3="U" />
        <X3 A0="P" A1="EMG_MEAN3X" A2="823230.982142856" A3="U" />
        <X3 A0="P" A1="EMG_3XLR" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XRL" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_3XDIF" A2="9999" A3="U" />
        <X3 A0="P" A1="EMG_AMPL" A2="692877.772619048" A3="U" />